// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         emails: ["emily.zhang@figma.com", "david.kim@vercel.com", "aisha.johnson@cloudflare.com"],
 *         webhookUrl: "https://api.yourapp.com/webhooks/enrich"
 *     }
 */
export interface BulkLookupRequest {
    /** Email addresses to look up (up to 100 000) */
    emails: string[];
    /**
     * A URL on your server where we should send webhook callbacks.
     * You'll receive one POST per email, plus one final completion POST.
     */
    webhookUrl?: string;
}
