// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         batchId: "665a1f4e2c3b7800129dce01"
 *     }
 */
export interface GetBulkLookupStatusRequest {
    /** The batch identifier returned when you submitted the job */
    batchId: string;
}
