// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         email: "emily.zhang@figma.com"
 *     }
 */
export interface LookupRequest {
    /** The email address to look up */
    email: string;
}
