// This file was auto-generated by Fern from our API Definition.

import { CompanyFollowersClient } from "./api/resources/companyFollowers/client/Client.js";
import { EmailFinderClient } from "./api/resources/emailFinder/client/Client.js";
import { EmailValidationClient } from "./api/resources/emailValidation/client/Client.js";
import { LeadFinderClient } from "./api/resources/leadFinder/client/Client.js";
import { PeopleSearchClient } from "./api/resources/peopleSearch/client/Client.js";
import { PhoneFinderClient } from "./api/resources/phoneFinder/client/Client.js";
import { ReverseEmailLookupClient } from "./api/resources/reverseEmailLookup/client/Client.js";
import { TeamsClient } from "./api/resources/teams/client/Client.js";
import { WalletsClient } from "./api/resources/wallets/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";

export declare namespace EnrichApiClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class EnrichApiClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<EnrichApiClient.Options>;
    protected _companyFollowers: CompanyFollowersClient | undefined;
    protected _emailValidation: EmailValidationClient | undefined;
    protected _emailFinder: EmailFinderClient | undefined;
    protected _phoneFinder: PhoneFinderClient | undefined;
    protected _reverseEmailLookup: ReverseEmailLookupClient | undefined;
    protected _wallets: WalletsClient | undefined;
    protected _teams: TeamsClient | undefined;
    protected _leadFinder: LeadFinderClient | undefined;
    protected _peopleSearch: PeopleSearchClient | undefined;

    constructor(options: EnrichApiClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get companyFollowers(): CompanyFollowersClient {
        return (this._companyFollowers ??= new CompanyFollowersClient(this._options));
    }

    public get emailValidation(): EmailValidationClient {
        return (this._emailValidation ??= new EmailValidationClient(this._options));
    }

    public get emailFinder(): EmailFinderClient {
        return (this._emailFinder ??= new EmailFinderClient(this._options));
    }

    public get phoneFinder(): PhoneFinderClient {
        return (this._phoneFinder ??= new PhoneFinderClient(this._options));
    }

    public get reverseEmailLookup(): ReverseEmailLookupClient {
        return (this._reverseEmailLookup ??= new ReverseEmailLookupClient(this._options));
    }

    public get wallets(): WalletsClient {
        return (this._wallets ??= new WalletsClient(this._options));
    }

    public get teams(): TeamsClient {
        return (this._teams ??= new TeamsClient(this._options));
    }

    public get leadFinder(): LeadFinderClient {
        return (this._leadFinder ??= new LeadFinderClient(this._options));
    }

    public get peopleSearch(): PeopleSearchClient {
        return (this._peopleSearch ??= new PeopleSearchClient(this._options));
    }
}
