// This file was auto-generated by Fern from our API Definition.

export interface AccessDeniedResponse {
    /** Error type URI */
    type: string;
    /** Error title */
    title: string;
    /** HTTP status code */
    status: number;
    /** Human-readable explanation */
    detail: string;
    /** Current access application status */
    accessStatus?: AccessDeniedResponse.AccessStatus | undefined;
}

export namespace AccessDeniedResponse {
    /** Current access application status */
    export const AccessStatus = {
        None: "none",
        Pending: "pending",
        Rejected: "rejected",
        Revoked: "revoked",
    } as const;
    export type AccessStatus = (typeof AccessStatus)[keyof typeof AccessStatus];
}
