// This file was auto-generated by Fern from our API Definition.

/**
 * Returned when you submit any batch job
 */
export interface BatchSubmitData {
    /** The unique identifier for this batch — use it to poll status and fetch results */
    batchId: string;
    /** The initial status (usually `queued`) */
    status: string;
    /** Number of unique items in the batch (after deduplication) */
    itemCount: number;
    /** How many items you submitted before deduplication */
    originalCount?: number | undefined;
    /** How many duplicate items were removed */
    duplicatesRemoved?: number | undefined;
}
