// This file was auto-generated by Fern from our API Definition.

/**
 * Progress information for a batch job
 */
export interface BatchStatusData {
    /** The batch identifier */
    batchId: string;
    /** Current status: `queued`, `processing`, `completed`, or `failed` */
    status: string;
    /** Total items in the batch */
    totalItems?: number | undefined;
    /** Items processed so far */
    processedItems?: number | undefined;
    /** Completion percentage (0–100) */
    progress?: number | undefined;
}
