// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface BatchSubmitResponse {
    success: true;
    data: EnrichApi.BatchSubmitData;
    meta?: EnrichApi.BatchSubmitMeta | undefined;
}
