// This file was auto-generated by Fern from our API Definition.

/**
 * Metadata returned when you submit a batch job
 */
export interface BatchSubmitMeta {
    /** Unique ID for this request */
    requestId?: string | undefined;
    /** Total credits reserved for the batch */
    creditsReserved?: number | undefined;
    /** Cost per item */
    creditsPerItem?: number | undefined;
    /** Estimated total cost (same as creditsReserved) */
    estimatedCredits?: number | undefined;
}
