// This file was auto-generated by Fern from our API Definition.

/**
 * Metadata returned when you fetch batch results (includes credit settlement)
 */
export interface BatchResultsMeta {
    /** Unique ID for this request */
    requestId?: string | undefined;
    /** Actual credits charged after settlement */
    creditsUsed?: number | undefined;
    /** Credits refunded (difference between reserved and actual cost) */
    creditsRefunded?: number | undefined;
    /** Your remaining credit balance after settlement */
    creditsRemaining?: number | undefined;
    /** Total items in the batch */
    totalItems?: number | undefined;
    /** Items that were processed */
    processedItems?: number | undefined;
}
