// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface BatchStatusResponse {
    success: true;
    data: EnrichApi.BatchStatusData;
    meta?: BatchStatusResponse.Meta | undefined;
}

export namespace BatchStatusResponse {
    export interface Meta {
        /** Request tracking ID */
        requestId?: string | undefined;
    }
}
