// This file was auto-generated by Fern from our API Definition.

/**
 * Returned when you submit a bulk reverse lookup
 */
export interface BulkLookupSubmitData {
    /** The batch identifier — use it to poll status and fetch results */
    batchId: string;
    status: string;
    /** Unique emails in the batch (after deduplication) */
    itemCount: number;
    message?: string | undefined;
    /** How many emails you submitted before deduplication */
    originalCount?: number | undefined;
    /** How many duplicate emails were removed */
    duplicatesRemoved?: number | undefined;
}
