// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface BulkLookupResponse {
    success: true;
    data: EnrichApi.BulkLookupSubmitData;
    meta?: EnrichApi.BatchSubmitMeta | undefined;
}
