// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface BulkLookupResultsResponse {
    success: true;
    data: BulkLookupResultsResponse.Data;
    meta?: EnrichApi.BatchResultsMeta | undefined;
}

export namespace BulkLookupResultsResponse {
    export interface Data {
        batchId: string;
        status: string;
        totalItems?: number | undefined;
        processedItems?: number | undefined;
        /** How many emails had a matching profile */
        successful?: number | undefined;
        /** How many emails had no matching profile */
        failed?: number | undefined;
        page?: number | undefined;
        limit?: number | undefined;
        results?: EnrichApi.ReverseLookupResult[] | undefined;
    }
}
