// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface CompanyFollowerResultsResponse {
    success: true;
    data: EnrichApi.CompanyFollowerResultsData;
    meta?: CompanyFollowerResultsResponse.Meta | undefined;
}

export namespace CompanyFollowerResultsResponse {
    export interface Meta {
        requestId?: string | undefined;
        /** Credits consumed (count × creditsPerItem) */
        creditsUsed?: number | undefined;
        /** Excess credits refunded */
        creditsRefunded?: number | undefined;
        /** Remaining credit balance */
        creditsRemaining?: number | undefined;
    }
}
