// This file was auto-generated by Fern from our API Definition.

export interface CompanyFollowerProgressData {
    /** Batch ID for this scrape job */
    batchId: string;
    /** Number of profiles processed so far */
    processed: number;
    /** Total profiles to process (-1 if unknown yet) */
    total: number;
    /** Number of errors encountered */
    errors: number;
    /** Whether scraping is complete */
    done: boolean;
    /** Human-readable status message */
    message?: string | undefined;
}
