// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface CompanyFollowerProgressResponse {
    success: true;
    data: EnrichApi.CompanyFollowerProgressData;
    meta?: CompanyFollowerProgressResponse.Meta | undefined;
}

export namespace CompanyFollowerProgressResponse {
    export interface Meta {
        requestId?: string | undefined;
    }
}
