// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface CompanyFollowerResultsData {
    /** Batch ID for this scrape job */
    batchId: string;
    /** Number of follower profiles in this page */
    count: number;
    /** Array of follower profiles */
    data: EnrichApi.FollowerProfile[];
    /** Pagination metadata */
    pagination: CompanyFollowerResultsData.Pagination;
}

export namespace CompanyFollowerResultsData {
    /**
     * Pagination metadata
     */
    export interface Pagination {
        /** Current page number */
        page: number;
        /** Results per page */
        limit: number;
        /** Total number of follower profiles */
        total: number;
        /** Total number of pages */
        totalPages: number;
    }
}
