// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface CountEstimateResultData {
    /** Total estimated follower count */
    totalCount: number;
    /** Breakdown by department/function (if departments filter was applied) */
    functionBreakdown?: (EnrichApi.FunctionBreakdownItem[] | null) | undefined;
    /** Breakdown by seniority level (if levels filter was applied) */
    seniorityBreakdown?: (EnrichApi.SeniorityBreakdownItem[] | null) | undefined;
    /** Filters applied to the estimation */
    filtersApplied?: (CountEstimateResultData.FiltersApplied | null) | undefined;
}

export namespace CountEstimateResultData {
    /**
     * Filters applied to the estimation
     */
    export interface FiltersApplied {
        countries?: string[] | undefined;
        jobTitles?: string[] | undefined;
        departments?: string[] | undefined;
        levels?: string[] | undefined;
    }
}
