// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface CountEstimateStatusData {
    /** Batch ID */
    batchId: string;
    /** Current job status */
    status: CountEstimateStatusData.Status;
    /** LinkedIn company URL */
    companyUrl: string;
    /** Human-readable status message */
    message?: string | undefined;
    /** When the job was created */
    createdAt: string;
    /** When the job completed */
    completedAt?: (string | null) | undefined;
    /** Result data (when completed) */
    data?: EnrichApi.CountEstimateResultData | undefined;
}

export namespace CountEstimateStatusData {
    /** Current job status */
    export const Status = {
        Pending: "pending",
        InProgress: "in_progress",
        Completed: "completed",
        Failed: "failed",
        Cancelled: "cancelled",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
