// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface CountEstimateStatusResponse {
    success: true;
    data: EnrichApi.CountEstimateStatusData;
    meta?: CountEstimateStatusResponse.Meta | undefined;
}

export namespace CountEstimateStatusResponse {
    export interface Meta {
        requestId?: string | undefined;
        /** Credits refunded (100, if job failed) */
        creditsRefunded?: number | undefined;
        /** Remaining credit balance */
        creditsRemaining?: number | undefined;
    }
}
