// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

/**
 * One entry in a person's education history
 */
export interface EducationHistoryItem {
    /** Degree or program name */
    degreeName?: string | undefined;
    startEndDate?: EnrichApi.StartEndDate | undefined;
    /** Name of the school */
    schoolName?: string | undefined;
    /** Where the school is located */
    schoolLocation?: string | undefined;
    /** URL of the school's logo */
    schoolLogo?: string | undefined;
}
