// This file was auto-generated by Fern from our API Definition.

/**
 * The result of searching for one person's email
 */
export interface EmailFinderResult {
    /** The first name you searched for */
    firstName: string;
    /** The last name you searched for */
    lastName: string;
    /** The domain you searched */
    domain: string;
    /** Whether we found an email for this person */
    found: boolean;
    /** The email address we found (only present when `found` is `true`) */
    email?: string | undefined;
    /** How confident we are that this is the right address */
    confidence?: EmailFinderResult.Confidence | undefined;
    /** Whether the domain is a catch-all (accepts any address) */
    isCatchAll?: boolean | undefined;
    /** The email provider detected for this domain (e.g. GOOGLE, MICROSOFT, ZOHO, FASTMAIL, PROTONMAIL) */
    provider?: string | undefined;
    /** A human-readable explanation */
    message: string;
}

export namespace EmailFinderResult {
    /** How confident we are that this is the right address */
    export const Confidence = {
        High: "high",
        Medium: "medium",
        Low: "low",
    } as const;
    export type Confidence = (typeof Confidence)[keyof typeof Confidence];
}
