// This file was auto-generated by Fern from our API Definition.

/**
 * The result of validating a single email address
 */
export interface EmailValidationResult {
    /** The email address that was validated */
    email: string;
    /**
     * The validation verdict:
     * - `valid` — the mailbox exists and accepts mail
     * - `invalid` — the mailbox does not exist
     * - `risky` — we can't confirm delivery (e.g. catch-all domain)
     */
    result: EmailValidationResult.Result;
    /** A human-readable explanation of the result */
    message: string;
    /** Whether the domain accepts mail to any address (catch-all) */
    isCatchAll: boolean;
    /** Whether the email uses SSO or federated authentication */
    isFederated?: boolean | undefined;
    /** Whether the domain uses a Secure Email Gateway */
    hasSEG?: boolean | undefined;
    /** The name of the Secure Email Gateway provider */
    segProvider?: string | undefined;
    /** The email service provider */
    provider?: EmailValidationResult.Provider | undefined;
    /**
     * How confident we are in the result:
     * - `definitive` — verified with certainty
     * - `high` — very likely correct
     * - `medium` — reasonably confident
     * - `low` — uncertain (often a catch-all domain)
     * - `temporary` — the server returned a temporary error
     * - `none` — no confidence data available
     */
    confidence: EmailValidationResult.Confidence;
}

export namespace EmailValidationResult {
    /**
     * The validation verdict:
     * - `valid` — the mailbox exists and accepts mail
     * - `invalid` — the mailbox does not exist
     * - `risky` — we can't confirm delivery (e.g. catch-all domain)
     */
    export const Result = {
        Valid: "valid",
        Invalid: "invalid",
        Risky: "risky",
    } as const;
    export type Result = (typeof Result)[keyof typeof Result];
    /** The email service provider */
    export const Provider = {
        Google: "GOOGLE",
        Microsoft: "MICROSOFT",
        Smtp: "SMTP",
    } as const;
    export type Provider = (typeof Provider)[keyof typeof Provider];
    /**
     * How confident we are in the result:
     * - `definitive` — verified with certainty
     * - `high` — very likely correct
     * - `medium` — reasonably confident
     * - `low` — uncertain (often a catch-all domain)
     * - `temporary` — the server returned a temporary error
     * - `none` — no confidence data available
     */
    export const Confidence = {
        Definitive: "definitive",
        High: "high",
        Medium: "medium",
        Low: "low",
        Temporary: "temporary",
        None: "none",
    } as const;
    export type Confidence = (typeof Confidence)[keyof typeof Confidence];
}
