// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface EmailValidationBatchResultsResponse {
    success: true;
    data: EmailValidationBatchResultsResponse.Data;
    meta?: EnrichApi.BatchResultsMeta | undefined;
}

export namespace EmailValidationBatchResultsResponse {
    export interface Data {
        /** The batch identifier */
        batchId: string;
        /** Final batch status */
        status: string;
        /** Total emails in the batch */
        totalItems?: number | undefined;
        /** Emails that were processed */
        processedCount?: number | undefined;
        /** The validation results */
        results?: EnrichApi.EmailValidationResult[] | undefined;
    }
}
