// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface EmailFinderBatchResultsResponse {
    success: true;
    data: EmailFinderBatchResultsResponse.Data;
    meta?: EnrichApi.BatchResultsMeta | undefined;
}

export namespace EmailFinderBatchResultsResponse {
    export interface Data {
        /** The batch identifier */
        batchId: string;
        /** Final batch status */
        status: string;
        /** Total leads in the batch */
        totalItems?: number | undefined;
        /** Leads that were processed */
        processedCount?: number | undefined;
        /** The finder results */
        results?: EnrichApi.EmailFinderResult[] | undefined;
    }
}
