// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface EmailValidationResponse {
    success: true;
    data: EnrichApi.EmailValidationResult;
    meta?: EnrichApi.EnrichmentMeta | undefined;
}
