// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface EmailFinderResponse {
    success: true;
    data: EnrichApi.EmailFinderResult;
    meta?: EnrichApi.EnrichmentMeta | undefined;
}
