// This file was auto-generated by Fern from our API Definition.

/**
 * Metadata included with every enrichment response
 */
export interface EnrichmentMeta {
    /** Unique ID for this request — useful for support tickets */
    requestId?: string | undefined;
    /** How many credits this request consumed */
    creditsUsed?: number | undefined;
    /** Your remaining credit balance after this request */
    creditsRemaining?: number | undefined;
    /** How long the lookup took, in milliseconds */
    processingTimeMs?: number | undefined;
}
