// This file was auto-generated by Fern from our API Definition.

/**
 * Standard error response envelope with success flag and error details.
 */
export interface ErrorEnvelope {
    /** Always false for error responses */
    success: boolean;
    error: ErrorEnvelope.Error_;
}

export namespace ErrorEnvelope {
    export interface Error_ {
        /** The HTTP status code */
        code: number;
        /** A short summary of the error */
        message: string;
        /** A human-readable explanation of what went wrong */
        detail?: string | undefined;
    }
}
