// This file was auto-generated by Fern from our API Definition.

export interface FollowerProfile {
    /** LinkedIn profile URN identifier */
    objectURN?: string | undefined;
    /** Full name */
    name?: (string | null) | undefined;
    /** First name */
    firstName?: (string | null) | undefined;
    /** Last name */
    lastName?: (string | null) | undefined;
    /** LinkedIn profile URL */
    profileUrl: string;
    /** Profile picture URL */
    profilePictureUrl?: (string | null) | undefined;
    /** Job title */
    title?: (string | null) | undefined;
    /** Current company name */
    companyName?: (string | null) | undefined;
    /** Company LinkedIn URL */
    companyProfileUrl?: (string | null) | undefined;
    /** Company website URL */
    companyWebsite?: (string | null) | undefined;
    /** Company domain */
    companyDomain?: (string | null) | undefined;
    /** Company logo URL */
    companyLogoUrl?: (string | null) | undefined;
    /** Company location */
    companyLocation?: (string | null) | undefined;
    /** Profile location */
    location?: (string | null) | undefined;
    /** Profile summary */
    summary?: (string | null) | undefined;
    /** Connection degree (1, 2, or 3) */
    connectionDegree?: (number | null) | undefined;
    /** Time at current company */
    tenureAtCompany?: (string | null) | undefined;
    /** Industry */
    industry?: (string | null) | undefined;
    /** Whether profile is Premium */
    isPremium?: (boolean | null) | undefined;
    /** Whether profile is Open Profile */
    isOpenProfile?: (boolean | null) | undefined;
    /** Whether profile is saved in Sales Navigator */
    isSaved?: (boolean | null) | undefined;
    /** Profile badges and highlights */
    spotlights?: string[] | undefined;
}
