// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface FunctionBreakdownItem {
    /** Job function name (e.g., Engineering) */
    functionName: string;
    /** Job function ID */
    functionId: string;
    /** Count of people in this function */
    count: number;
    /** Percentage of total */
    percentage: number;
    /** Nested seniority breakdown within this department */
    seniorityBreakdown?: (EnrichApi.SeniorityBreakdownItem[] | null) | undefined;
}
