// This file was auto-generated by Fern from our API Definition.

export interface Invitation {
    id: string;
    /** Who was invited */
    email: string;
    /** The role they'll have when they accept */
    role: Invitation.Role;
    /** Invitation status (always `pending` for outstanding invitations) */
    status: "pending";
    /** When the invitation expires */
    expiresAt: string;
    /** When the invitation was sent */
    createdAt: string;
}

export namespace Invitation {
    /** The role they'll have when they accept */
    export const Role = {
        Admin: "admin",
        Member: "member",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
}
