// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface LeadEnrichResponse {
    success: true;
    data: LeadEnrichResponse.Data;
    meta?: LeadEnrichResponse.Meta | undefined;
}

export namespace LeadEnrichResponse {
    export interface Data {
        results: EnrichApi.LeadEnrichResult[];
        alreadyRevealed: number;
        newlyRevealed: number;
    }

    export interface Meta {
        requestId?: string | undefined;
        creditsUsed?: number | undefined;
        creditsRemaining?: number | undefined;
        pricing?: Meta.Pricing | undefined;
    }

    export namespace Meta {
        export interface Pricing {
            email?: number | undefined;
            phone?: number | undefined;
        }
    }
}
