// This file was auto-generated by Fern from our API Definition.

export interface LeadSearchPreviewResult {
    /** Encrypted lead identifier — use this for reveal/enrich/export */
    id: string;
    /** First name */
    firstName?: (string | null) | undefined;
    /** Last name (masked until unlocked) */
    lastName?: (string | null) | undefined;
    /** Company logo URL */
    logoUrl?: (string | null) | undefined;
    /** Email domain */
    emailDomain?: (string | null) | undefined;
    /** LinkedIn profile URL */
    linkedinUrl?: (string | null) | undefined;
    /** LinkedIn headline */
    linkedinHeadline?: (string | null) | undefined;
    /** Job title */
    jobTitle?: (string | null) | undefined;
    /** Job function/department */
    jobFunction?: (string | null) | undefined;
    /** Job level/seniority */
    jobLevel?: (string | null) | undefined;
    /** Company name */
    companyName?: (string | null) | undefined;
    /** Skills */
    skills?: (string | null) | undefined;
    /** Person city */
    city?: (string | null) | undefined;
    /** State/province */
    stateName?: (string | null) | undefined;
    /** Country */
    countryName?: (string | null) | undefined;
    /** Company domain */
    domain?: (string | null) | undefined;
    /** Organization LinkedIn URL */
    orgLinkedinUrl?: (string | null) | undefined;
    /** Employee count */
    employeeCount?: (number | null) | undefined;
    /** SIC industry */
    industrySicDescription?: (string | null) | undefined;
    /** NAICS industry */
    industryNaicsDescription?: (string | null) | undefined;
    /** Revenue range */
    revenue?: (string | null) | undefined;
    /** Company specialties */
    specialties?: (string | null) | undefined;
    /** Founded date */
    foundedOn?: (string | null) | undefined;
    /** HQ city */
    headquartersCity?: (string | null) | undefined;
    /** HQ state */
    headquartersState?: (string | null) | undefined;
    /** HQ country */
    headquartersCountry?: (string | null) | undefined;
    /** Employee on LinkedIn growth rate */
    employeeOnLinkedinGrowthRateOrg?: (number | null) | undefined;
    /** Total monthly website traffic */
    totalMonthlyTrafficOrg?: (number | null) | undefined;
    /** Total funding amount */
    totalFundingAmountOrg?: (number | null) | undefined;
    /** Last funding type */
    lastFundingTypeOrg?: (string | null) | undefined;
    /** Last funding date */
    lastFundingDateOrg?: (string | null) | undefined;
}
