// This file was auto-generated by Fern from our API Definition.

export interface LeadEnrichResult {
    /** Lead ID */
    id: string;
    firstName?: (string | null) | undefined;
    lastName?: (string | null) | undefined;
    companyName?: (string | null) | undefined;
    jobTitle?: (string | null) | undefined;
    /** Email address (if requested) */
    email?: (string | null) | undefined;
    /** Phone number (if requested) */
    phone?: (string | null) | undefined;
    /** Cellphone (if requested) */
    cellphone?: (string | null) | undefined;
}
