// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface LeadRevealResponse {
    success: true;
    data: LeadRevealResponse.Data;
    meta?: LeadRevealResponse.Meta | undefined;
}

export namespace LeadRevealResponse {
    export interface Data {
        /** Revealed contacts */
        revealed: EnrichApi.RevealedContact[];
        /** Count of leads already revealed (not re-charged) */
        alreadyRevealed: number;
        /** Count of leads newly revealed (charged) */
        newlyRevealed: number;
    }

    export interface Meta {
        requestId?: string | undefined;
        /** Credits consumed for new reveals */
        creditsUsed?: number | undefined;
        /** Remaining workspace credit balance */
        creditsRemaining?: number | undefined;
    }
}
