// This file was auto-generated by Fern from our API Definition.

export interface LeadFinderPagination {
    /** Current page number */
    page: number;
    /** Results per page */
    pageSize: number;
    /** Total matching results */
    totalResults: number;
    /** Total pages available */
    totalPages: number;
    /** Whether more pages exist */
    hasMore: boolean;
}
