// This file was auto-generated by Fern from our API Definition.

export interface LeadFinderSuggestResponse {
    success: true;
    data: LeadFinderSuggestResponse.Data;
    meta?: LeadFinderSuggestResponse.Meta | undefined;
}

export namespace LeadFinderSuggestResponse {
    export interface Data {
        /** Matching company names */
        values: string[];
    }

    export interface Meta {
        requestId?: string | undefined;
    }
}
