// This file was auto-generated by Fern from our API Definition.

export interface LeadFinderFilterOptionsResponse {
    success: true;
    /** Object keyed by filter field name, each containing an array of available values */
    data: Record<string, string[]>;
    meta?: LeadFinderFilterOptionsResponse.Meta | undefined;
}

export namespace LeadFinderFilterOptionsResponse {
    export interface Meta {
        requestId?: string | undefined;
    }
}
