// This file was auto-generated by Fern from our API Definition.

export interface LeadFinderDeletedResponse {
    success: true;
    data: LeadFinderDeletedResponse.Data;
    meta?: LeadFinderDeletedResponse.Meta | undefined;
}

export namespace LeadFinderDeletedResponse {
    export interface Data {
        deleted: true;
    }

    export interface Meta {
        requestId?: string | undefined;
    }
}
