// This file was auto-generated by Fern from our API Definition.

/**
 * A single person to find an email for
 */
export interface Lead {
    /** First name */
    firstName: string;
    /** Last name */
    lastName: string;
    /** Company domain */
    domain: string;
}
