// This file was auto-generated by Fern from our API Definition.

export interface LeadCountResponse {
    success: true;
    data: LeadCountResponse.Data;
    meta?: LeadCountResponse.Meta | undefined;
}

export namespace LeadCountResponse {
    export interface Data {
        /** Estimated result count */
        count: number;
        /** Type of search performed */
        searchType: Data.SearchType;
    }

    export namespace Data {
        /** Type of search performed */
        export const SearchType = {
            People: "people",
            Company: "company",
            Unified: "unified",
        } as const;
        export type SearchType = (typeof SearchType)[keyof typeof SearchType];
    }

    export interface Meta {
        requestId?: string | undefined;
    }
}
