// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface LeadSearchResponse {
    success: true;
    data: LeadSearchResponse.Data;
    meta?: LeadSearchResponse.Meta | undefined;
}

export namespace LeadSearchResponse {
    export interface Data {
        /** Array of search results */
        results: EnrichApi.LeadSearchPreviewResult[];
        /** Pagination metadata */
        pagination: EnrichApi.LeadFinderPagination;
    }

    export interface Meta {
        /** Request tracking ID */
        requestId?: string | undefined;
    }
}
