// This file was auto-generated by Fern from our API Definition.

/**
 * Comprehensive search filters for unified lead finder. All fields are optional. Supports ~135 filter fields across person, organization, and insights dimensions.
 */
export interface LeadFinderSearchFilters {
    /** First name (exact match) */
    firstName?: string | undefined;
    /** Last name (exact match) */
    lastName?: string | undefined;
    /** Middle name (exact match) */
    middleName?: string | undefined;
    /** Person city (exact match) */
    city?: string | undefined;
    /** State/province name (multi-select) */
    stateName?: LeadFinderSearchFilters.StateName | undefined;
    /** State/province code (multi-select) */
    stateCode?: LeadFinderSearchFilters.StateCode | undefined;
    /** Country name (multi-select) */
    countryName?: LeadFinderSearchFilters.CountryName | undefined;
    /** Country code (multi-select) */
    countryCode?: LeadFinderSearchFilters.CountryCode | undefined;
    /** Continent (multi-select) */
    continent?: LeadFinderSearchFilters.Continent | undefined;
    /** Country region/area (multi-select) */
    countryRegion?: LeadFinderSearchFilters.CountryRegion | undefined;
    /** LinkedIn profile URL (exact match) */
    linkedinUrl?: string | undefined;
    /** LinkedIn headline (exact match) */
    linkedinHeadline?: string | undefined;
    /** LinkedIn industry (exact match) */
    linkedinIndustry?: string | undefined;
    /** Person logo URL (exact match) */
    logoUrl?: string | undefined;
    /** Email domain (exact match) */
    emailDomain?: string | undefined;
    /** Email address (exact match) */
    emailAddress?: string | undefined;
    /** Job title (multi-select, exact match) */
    jobTitle?: LeadFinderSearchFilters.JobTitle | undefined;
    /** Job function (multi-select). E.g. ['Engineering', 'Marketing'] */
    jobFunction?: LeadFinderSearchFilters.JobFunction | undefined;
    /** Job level/seniority (multi-select). E.g. ['C-Suite', 'VP', 'Director'] */
    jobLevel?: LeadFinderSearchFilters.JobLevel | undefined;
    /** Job description (exact match) */
    jobDescription?: string | undefined;
    /** Job location city (exact match) */
    jobLocationCity?: string | undefined;
    /** Job location state (exact match) */
    jobLocationState?: string | undefined;
    /** Job location country (multi-select) */
    jobLocationCountry?: LeadFinderSearchFilters.JobLocationCountry | undefined;
    /** Whether job is current position */
    jobIsCurrent?: boolean | undefined;
    /** Job start date (exact match) */
    jobStartDate?: string | undefined;
    /** Min number of jobs in profile */
    jobCount?: number | undefined;
    /** Company name from person record (multi-select, exact match via suggest) */
    companyName?: LeadFinderSearchFilters.CompanyName | undefined;
    /** Company name match mode: exact (IN) or contains (ILIKE) */
    companyNameMode?: LeadFinderSearchFilters.CompanyNameMode | undefined;
    /** Persona type (exact match) */
    persona?: string | undefined;
    /** Languages (exact match) */
    languages?: string | undefined;
    /** Skills (multi-select, exact match) */
    skills?: LeadFinderSearchFilters.Skills | undefined;
    /** Certifications (exact match) */
    certifications?: string | undefined;
    /** Patents (exact match) */
    patents?: string | undefined;
    /** Publications (exact match) */
    publications?: string | undefined;
    /** Websites (exact match) */
    websites?: string | undefined;
    /** Education (exact match) */
    education?: string | undefined;
    /** Phone number (exact match) */
    phone?: string | undefined;
    /** Cellphone number (exact match) */
    cellphone?: string | undefined;
    /** Organization name (exact match) */
    orgName?: string | undefined;
    /** Company domain (multi-select, max 500) */
    domain?: LeadFinderSearchFilters.Domain | undefined;
    /** Company about us (exact match) */
    aboutUs?: string | undefined;
    /** Company entity type (multi-select) */
    companyEntityType?: LeadFinderSearchFilters.CompanyEntityType | undefined;
    /** Company legal type (multi-select) */
    companyLegalType?: LeadFinderSearchFilters.CompanyLegalType | undefined;
    /** Min employee count */
    employeeCount?: number | undefined;
    /** Max employee count upper bound */
    employeeCountMax?: number | undefined;
    /** Min employee count lower bound */
    employeeCountMin?: number | undefined;
    /** Founded year (exact match, e.g. 2020) */
    foundedOn?: number | undefined;
    /** Headquarters city (exact match) */
    headquartersCity?: string | undefined;
    /** Headquarters state (exact match) */
    headquartersState?: string | undefined;
    /** Headquarters country (multi-select) */
    headquartersCountry?: LeadFinderSearchFilters.HeadquartersCountry | undefined;
    /** SIC industry code (multi-select) */
    industrySicCode?: LeadFinderSearchFilters.IndustrySicCode | undefined;
    /** SIC industry description (multi-select) */
    industrySicDescription?: LeadFinderSearchFilters.IndustrySicDescription | undefined;
    /** NAICS industry code (multi-select) */
    industryNaicsCode?: LeadFinderSearchFilters.IndustryNaicsCode | undefined;
    /** NAICS industry description (multi-select) */
    industryNaicsDescription?: LeadFinderSearchFilters.IndustryNaicsDescription | undefined;
    /** Organization LinkedIn URL (exact match) */
    orgLinkedinUrl?: string | undefined;
    /** Organization location city (exact match) */
    locationCity?: string | undefined;
    /** Organization location state (exact match) */
    locationState?: string | undefined;
    /** Organization location country (multi-select) */
    locationCountry?: LeadFinderSearchFilters.LocationCountry | undefined;
    /** Max revenue upper bound */
    revenueMax?: number | undefined;
    /** Min revenue lower bound */
    revenueMin?: number | undefined;
    /** Company specialties (exact match) */
    specialties?: string | undefined;
    /** CRM technology (multi-select) */
    crmTechOrg?: LeadFinderSearchFilters.CrmTechOrg | undefined;
    /** Marketing automation technology (multi-select) */
    marketingAutomationTechOrg?: LeadFinderSearchFilters.MarketingAutomationTechOrg | undefined;
    /** ABM technology (multi-select) */
    abmTechOrg?: LeadFinderSearchFilters.AbmTechOrg | undefined;
    /** Sales automation technology (multi-select) */
    salesAutomationTechOrg?: LeadFinderSearchFilters.SalesAutomationTechOrg | undefined;
    /** Analytics technology (multi-select) */
    analyticsTechOrg?: LeadFinderSearchFilters.AnalyticsTechOrg | undefined;
    /** CMS technology (multi-select) */
    cmsTechOrg?: LeadFinderSearchFilters.CmsTechOrg | undefined;
    /** Martech categories (exact match) */
    martechCategoriesOrg?: string | undefined;
    /** Conversation intelligence technology (multi-select) */
    conversationIntelligenceTechOrg?: LeadFinderSearchFilters.ConversationIntelligenceTechOrg | undefined;
    /** Cloud provider technology (multi-select) */
    cloudProviderTechOrg?: LeadFinderSearchFilters.CloudProviderTechOrg | undefined;
    /** Email hosting technology (multi-select) */
    emailHostingTechOrg?: LeadFinderSearchFilters.EmailHostingTechOrg | undefined;
    /** Email security technology (multi-select) */
    emailSecurityTechOrg?: LeadFinderSearchFilters.EmailSecurityTechOrg | undefined;
    /** Application security technology (multi-select) */
    applicationSecurityTechOrg?: LeadFinderSearchFilters.ApplicationSecurityTechOrg | undefined;
    /** Cloud security technology (multi-select) */
    cloudSecurityTechOrg?: LeadFinderSearchFilters.CloudSecurityTechOrg | undefined;
    /** Development technology (multi-select) */
    developmentTechOrg?: LeadFinderSearchFilters.DevelopmentTechOrg | undefined;
    /** E-commerce platform technology (multi-select) */
    eCommercePlatformTechOrg?: LeadFinderSearchFilters.ECommercePlatformTechOrg | undefined;
    /** ERP technology (multi-select) */
    erpTechOrg?: LeadFinderSearchFilters.ErpTechOrg | undefined;
    /** Has mobile app */
    hasMobileAppOrg?: boolean | undefined;
    /** Has web app */
    hasWebAppOrg?: boolean | undefined;
    /** Has CISO */
    hasCisoOrg?: boolean | undefined;
    /** Has CIO */
    hasCioOrg?: boolean | undefined;
    /** Min location count */
    locationCountOrg?: number | undefined;
    /** LinkedIn URL is claimed */
    isLinkedinUrlClaimedOrg?: boolean | undefined;
    /** Min marketing role count */
    marketingRoleCountOrg?: number | undefined;
    /** Min sales role count */
    salesRoleCountOrg?: number | undefined;
    /** Min operations role count */
    operationsRoleCountOrg?: number | undefined;
    /** Min business development role count */
    businessDevelopmentRoleCountOrg?: number | undefined;
    /** Min customer success role count */
    customerSuccessRoleCountOrg?: number | undefined;
    /** Min IT role count */
    itRoleCountOrg?: number | undefined;
    /** Min GRC role count */
    grcRoleCountOrg?: number | undefined;
    /** Min security role count */
    securityRoleCountOrg?: number | undefined;
    /** Min DevOps role count */
    devopsRoleCountOrg?: number | undefined;
    /** Min network infrastructure role count */
    networkInfrastructureRoleCountOrg?: number | undefined;
    /** Min mobile dev role count */
    mobileDevRoleCountOrg?: number | undefined;
    /** Min iOS dev role count */
    iosDevRoleCountOrg?: number | undefined;
    /** Min Android dev role count */
    androidDevRoleCountOrg?: number | undefined;
    /** Min engineer role count */
    engineerRoleCountOrg?: number | undefined;
    /** Min QA role count */
    qaRoleCountOrg?: number | undefined;
    /** Min marketing open roles count */
    marketingOpenRolesCountOrg?: number | undefined;
    /** Min operations open roles count */
    operationsOpenRolesCountOrg?: number | undefined;
    /** Min sales open roles count */
    salesOpenRolesCountOrg?: number | undefined;
    /** Min account executive open roles count */
    accountExecutiveOpenRolesCountOrg?: number | undefined;
    /** Min customer success open roles count */
    customerSuccessOpenRolesCountOrg?: number | undefined;
    /** Min demand generation open roles count */
    demandGenerationOpenRolesCountOrg?: number | undefined;
    /** Min business development open roles count */
    businessDevelopmentOpenRolesCountOrg?: number | undefined;
    /** Min IT open roles count */
    itOpenRolesCountOrg?: number | undefined;
    /** Min security open roles count */
    securityOpenRolesCountOrg?: number | undefined;
    /** Min GRC open roles count */
    grcOpenRolesCountOrg?: number | undefined;
    /** Min DevOps open roles count */
    devopsOpenRolesCountOrg?: number | undefined;
    /** Min network infrastructure open roles count */
    networkInfrastructureOpenRolesCountOrg?: number | undefined;
    /** Min monthly organic traffic */
    monthlyOrganicTrafficOrg?: number | undefined;
    /** Min monthly paid traffic */
    monthlyPaidTrafficOrg?: number | undefined;
    /** Min total monthly traffic */
    totalMonthlyTrafficOrg?: number | undefined;
    /** Min monthly Google ad spend */
    monthlyGoogleAdspendOrg?: number | undefined;
    /** Min employee on LinkedIn growth rate */
    employeeOnLinkedinGrowthRateOrg?: number | undefined;
    /** Website is for sale */
    isWebsiteForSaleOrg?: boolean | undefined;
    /** Top Apple App Store URL (exact match) */
    topAppleappstoreUrlOrg?: string | undefined;
    /** Min App Store rating */
    topAppstoreRatingOrg?: number | undefined;
    /** Min App Store review count */
    topAppstoreReviewCountOrg?: number | undefined;
    /** Last App Store update date (exact match) */
    lastAppstoreUpdateOrg?: string | undefined;
    /** Min App Store update count */
    appstoreUpdateCountOrg?: number | undefined;
    /** App Store app category (exact match) */
    appstoreAppCategoryOrg?: string | undefined;
    /** Top Play Store URL (exact match) */
    topPlaystoreUrlOrg?: string | undefined;
    /** Min Play Store rating */
    topPlaystoreRatingOrg?: number | undefined;
    /** Min Play Store review count */
    topPlaystoreReviewCountOrg?: number | undefined;
    /** Last Play Store update date (exact match) */
    lastPlaystoreUpdateOrg?: string | undefined;
    /** Min Play Store download count */
    playstoreDownloadCountOrg?: number | undefined;
    /** Play Store app category (exact match) */
    playstoreAppCategoryOrg?: string | undefined;
    /** Min total reviews count */
    totalReviewsOrg?: number | undefined;
    /** Last funding date (exact match) */
    lastFundingDateOrg?: string | undefined;
    /** Min last funding amount */
    lastFundingAmountOrg?: number | undefined;
    /** Lead investors (exact match) */
    leadInvestorsOrg?: string | undefined;
    /** Last funding type (multi-select). E.g. ['Series A', 'Series B'] */
    lastFundingTypeOrg?: LeadFinderSearchFilters.LastFundingTypeOrg | undefined;
    /** Min funding round number of investors */
    fundingRoundNumberOfInvestorsOrg?: number | undefined;
    /** Min total funding amount */
    totalFundingAmountOrg?: number | undefined;
}

export namespace LeadFinderSearchFilters {
    /**
     * State/province name (multi-select)
     */
    export type StateName = string | string[];
    /**
     * State/province code (multi-select)
     */
    export type StateCode = string | string[];
    /**
     * Country name (multi-select)
     */
    export type CountryName = string | string[];
    /**
     * Country code (multi-select)
     */
    export type CountryCode = string | string[];
    /**
     * Continent (multi-select)
     */
    export type Continent = string | string[];
    /**
     * Country region/area (multi-select)
     */
    export type CountryRegion = string | string[];
    /**
     * Job title (multi-select, exact match)
     */
    export type JobTitle = string | string[];
    /**
     * Job function (multi-select). E.g. ['Engineering', 'Marketing']
     */
    export type JobFunction = string | string[];
    /**
     * Job level/seniority (multi-select). E.g. ['C-Suite', 'VP', 'Director']
     */
    export type JobLevel = string | string[];
    /**
     * Job location country (multi-select)
     */
    export type JobLocationCountry = string | string[];
    /**
     * Company name from person record (multi-select, exact match via suggest)
     */
    export type CompanyName = string | string[];
    /** Company name match mode: exact (IN) or contains (ILIKE) */
    export const CompanyNameMode = {
        Exact: "exact",
        Contains: "contains",
    } as const;
    export type CompanyNameMode = (typeof CompanyNameMode)[keyof typeof CompanyNameMode];
    /**
     * Skills (multi-select, exact match)
     */
    export type Skills = string | string[];
    /**
     * Company domain (multi-select, max 500)
     */
    export type Domain = string | string[];
    /**
     * Company entity type (multi-select)
     */
    export type CompanyEntityType = string | string[];
    /**
     * Company legal type (multi-select)
     */
    export type CompanyLegalType = string | string[];
    /**
     * Headquarters country (multi-select)
     */
    export type HeadquartersCountry = string | string[];
    /**
     * SIC industry code (multi-select)
     */
    export type IndustrySicCode = string | string[];
    /**
     * SIC industry description (multi-select)
     */
    export type IndustrySicDescription = string | string[];
    /**
     * NAICS industry code (multi-select)
     */
    export type IndustryNaicsCode = string | string[];
    /**
     * NAICS industry description (multi-select)
     */
    export type IndustryNaicsDescription = string | string[];
    /**
     * Organization location country (multi-select)
     */
    export type LocationCountry = string | string[];
    /**
     * CRM technology (multi-select)
     */
    export type CrmTechOrg = string | string[];
    /**
     * Marketing automation technology (multi-select)
     */
    export type MarketingAutomationTechOrg = string | string[];
    /**
     * ABM technology (multi-select)
     */
    export type AbmTechOrg = string | string[];
    /**
     * Sales automation technology (multi-select)
     */
    export type SalesAutomationTechOrg = string | string[];
    /**
     * Analytics technology (multi-select)
     */
    export type AnalyticsTechOrg = string | string[];
    /**
     * CMS technology (multi-select)
     */
    export type CmsTechOrg = string | string[];
    /**
     * Conversation intelligence technology (multi-select)
     */
    export type ConversationIntelligenceTechOrg = string | string[];
    /**
     * Cloud provider technology (multi-select)
     */
    export type CloudProviderTechOrg = string | string[];
    /**
     * Email hosting technology (multi-select)
     */
    export type EmailHostingTechOrg = string | string[];
    /**
     * Email security technology (multi-select)
     */
    export type EmailSecurityTechOrg = string | string[];
    /**
     * Application security technology (multi-select)
     */
    export type ApplicationSecurityTechOrg = string | string[];
    /**
     * Cloud security technology (multi-select)
     */
    export type CloudSecurityTechOrg = string | string[];
    /**
     * Development technology (multi-select)
     */
    export type DevelopmentTechOrg = string | string[];
    /**
     * E-commerce platform technology (multi-select)
     */
    export type ECommercePlatformTechOrg = string | string[];
    /**
     * ERP technology (multi-select)
     */
    export type ErpTechOrg = string | string[];
    /**
     * Last funding type (multi-select). E.g. ['Series A', 'Series B']
     */
    export type LastFundingTypeOrg = string | string[];
}
