// This file was auto-generated by Fern from our API Definition.

export interface Pagination {
    /** The page you're on */
    page: number;
    /** Items per page */
    limit: number;
    /** Total items across all pages */
    total: number;
    /** Total number of pages */
    totalPages: number;
}
