// This file was auto-generated by Fern from our API Definition.

/**
 * Returned when you submit a bulk phone lookup job
 */
export interface PhoneBulkJobSubmitData {
    /** The job identifier — use it to poll status and fetch results */
    batchId: string;
    status: string;
    /** Unique items in the job (after deduplication) */
    itemCount: number;
    message?: string | undefined;
    /** How many items you submitted before deduplication */
    originalCount?: number | undefined;
    /** How many duplicates were removed */
    duplicatesRemoved?: number | undefined;
}
