// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface PhoneLookupResponse {
    success: true;
    data: EnrichApi.PhoneLookupResult;
    meta?: EnrichApi.EnrichmentMeta | undefined;
}
