// This file was auto-generated by Fern from our API Definition.

/**
 * One result from a bulk phone lookup
 */
export interface PhoneBulkResultItem {
    /** The email address that was looked up (if the item was an email) */
    email?: string | undefined;
    /** The profile URL that was looked up (if the item was a profile URL) */
    linkedin?: string | undefined;
    /** Phone numbers found for this person (empty if none found) */
    phones?: string[] | undefined;
    /** An error message if the lookup failed for this item */
    error?: string | undefined;
}
