// This file was auto-generated by Fern from our API Definition.

export interface PhoneBulkJobStatusData {
    batchId: string;
    status: string;
    totalItems?: number | undefined;
    processedItems?: number | undefined;
    /** Completion percentage (0–100) */
    progress?: number | undefined;
}
