// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface PhoneBulkJobResultsResponse {
    success: true;
    data: PhoneBulkJobResultsResponse.Data;
    meta?: EnrichApi.BatchResultsMeta | undefined;
}

export namespace PhoneBulkJobResultsResponse {
    export interface Data {
        batchId: string;
        status: string;
        totalItems?: number | undefined;
        processedItems?: number | undefined;
        /** Items where at least one phone was found */
        successful?: number | undefined;
        /** Items where no phone was found or the lookup errored */
        failed?: number | undefined;
        results?: EnrichApi.PhoneBulkResultItem[] | undefined;
        page?: number | undefined;
        limit?: number | undefined;
    }
}
