// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface PhoneBulkJobSubmitResponse {
    success: true;
    data: EnrichApi.PhoneBulkJobSubmitData;
    meta?: EnrichApi.BatchSubmitMeta | undefined;
}
