// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface PhoneBulkJobStatusResponse {
    success: true;
    data: EnrichApi.PhoneBulkJobStatusData;
    meta?: PhoneBulkJobStatusResponse.Meta | undefined;
}

export namespace PhoneBulkJobStatusResponse {
    export interface Meta {
        requestId?: string | undefined;
    }
}
