// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

/**
 * One entry in a person's work history
 */
export interface PositionHistoryItem {
    /** Job title */
    title?: string | undefined;
    startEndDate?: EnrichApi.StartEndDate | undefined;
    /** What the person did in this role */
    description?: string | undefined;
    /** Company name */
    companyName?: string | undefined;
    /** Where the company is located */
    companyLocation?: string | undefined;
    /** URL of the company's logo */
    companyLogo?: string | undefined;
}
