// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

/**
 * Professional profile data for a person
 */
export interface ReverseLookupResult {
    /** Profile identifier */
    id?: string | undefined;
    /** Full name */
    displayName?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    /** Professional headline */
    headline?: string | undefined;
    /** About section from their profile */
    summary?: string | undefined;
    /** Current company */
    companyName?: string | undefined;
    /** Where they are based */
    location?: string | undefined;
    /** Profile photo URL */
    photoUrl?: string | undefined;
    /** Profile URL */
    profileUrl?: string | undefined;
    /** URL to report this profile */
    reportProfileUrl?: string | undefined;
    /** Number of connections */
    connectionCount?: number | undefined;
    /** Whether the connection count is approximate (shows "500+" for large networks) */
    isConnectionCountObfuscated?: boolean | undefined;
    /** Whether the profile is publicly visible */
    isPublic?: boolean | undefined;
    /** Skills listed on the profile */
    skills?: string[] | undefined;
    /** Language and country */
    locale?: ReverseLookupResult.Locale | undefined;
    /** Education history */
    schools?: ReverseLookupResult.Schools | undefined;
    /** Work experience */
    positions?: ReverseLookupResult.Positions | undefined;
    /** Credits charged for this lookup */
    creditsConsumed?: number | undefined;
}

export namespace ReverseLookupResult {
    /**
     * Language and country
     */
    export interface Locale {
        country?: string | undefined;
        language?: string | undefined;
    }

    /**
     * Education history
     */
    export interface Schools {
        educationsCount?: number | undefined;
        educationHistory?: EnrichApi.EducationHistoryItem[] | undefined;
    }

    /**
     * Work experience
     */
    export interface Positions {
        positionsCount?: number | undefined;
        positionHistory?: EnrichApi.PositionHistoryItem[] | undefined;
    }
}
