// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface ReverseLookupResponse {
    success: true;
    data: EnrichApi.ReverseLookupResult;
    meta?: EnrichApi.EnrichmentMeta | undefined;
}
