// This file was auto-generated by Fern from our API Definition.

export interface RevealedContact {
    /** Encrypted lead identifier */
    id: string;
    /** First name */
    firstName?: (string | null) | undefined;
    /** Last name */
    lastName?: (string | null) | undefined;
    /** Job title */
    jobTitle?: (string | null) | undefined;
    /** Company name */
    companyName?: (string | null) | undefined;
    /** Email address (revealed) */
    emailAddress?: (string | null) | undefined;
    /** Phone number (revealed) */
    phone?: (string | null) | undefined;
    /** Cellphone number (revealed) */
    cellphone?: (string | null) | undefined;
    /** LinkedIn profile URL */
    linkedinUrl?: (string | null) | undefined;
    /** Company domain */
    domain?: (string | null) | undefined;
}
