// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface SavedSearchListResponse {
    success: true;
    data: EnrichApi.SavedSearchItem[];
    meta?: SavedSearchListResponse.Meta | undefined;
}

export namespace SavedSearchListResponse {
    export interface Meta {
        requestId?: string | undefined;
    }
}
