// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface SavedSearchItem {
    /** Saved search ID */
    id: string;
    /** Search name */
    name: string;
    /** Saved search filters */
    filters: EnrichApi.LeadFinderSearchFilters;
    /** Creation timestamp */
    createdAt: string;
    /** Last update timestamp */
    updatedAt: string;
}
