// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface SavedSearchResponse {
    success: true;
    data: EnrichApi.SavedSearchItem;
    meta?: SavedSearchResponse.Meta | undefined;
}

export namespace SavedSearchResponse {
    export interface Meta {
        requestId?: string | undefined;
    }
}
