// This file was auto-generated by Fern from our API Definition.

export interface SeniorityBreakdownItem {
    /** Seniority level name (e.g., Director) */
    seniorityLevel: string;
    /** Seniority level ID */
    seniorityId: string;
    /** Count of people at this seniority */
    count: number;
    /** Percentage of total */
    percentage: number;
}
