// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface StartCountEstimateResponse {
    success: true;
    data: EnrichApi.StartCountEstimateData;
    meta?: StartCountEstimateResponse.Meta | undefined;
}

export namespace StartCountEstimateResponse {
    export interface Meta {
        requestId?: string | undefined;
        /** Credits consumed (100, or 0 if from cache) */
        creditsUsed?: number | undefined;
        /** Remaining credit balance */
        creditsRemaining?: number | undefined;
    }
}
