// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface StartCountEstimateData {
    /** Unique batch ID for this estimation */
    batchId: string;
    /** Job status — pending (queued) or completed (from cache) */
    status: StartCountEstimateData.Status;
    /** Human-readable status message */
    message?: string | undefined;
    /** Whether result was served from cache (no credits charged) */
    fromCache?: boolean | undefined;
    /** When the cached result was originally computed */
    cachedAt?: string | undefined;
    /** Result data (only present if returned from cache) */
    data?: EnrichApi.CountEstimateResultData | undefined;
}

export namespace StartCountEstimateData {
    /** Job status — pending (queued) or completed (from cache) */
    export const Status = {
        Pending: "pending",
        Completed: "completed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
