// This file was auto-generated by Fern from our API Definition.

export interface StartCompanyFollowerData {
    /** Unique batch ID for tracking this scrape job */
    batchId: string;
    /** Human-readable status message */
    message: string;
}
