// This file was auto-generated by Fern from our API Definition.

/**
 * A date range (used for job history and education)
 */
export interface StartEndDate {
    start?: StartEndDate.Start | undefined;
    /** `null` means the person is still in this role or program */
    end?: (StartEndDate.End | null) | undefined;
}

export namespace StartEndDate {
    export interface Start {
        month?: number | undefined;
        year?: number | undefined;
    }

    /**
     * `null` means the person is still in this role or program
     */
    export interface End {
        month?: number | undefined;
        year?: number | undefined;
    }
}
