// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface StartCompanyFollowerResponse {
    success: true;
    data: EnrichApi.StartCompanyFollowerData;
    meta?: StartCompanyFollowerResponse.Meta | undefined;
}

export namespace StartCompanyFollowerResponse {
    export interface Meta {
        requestId?: string | undefined;
        /** Credits reserved upfront based on max_limit × creditsPerItem */
        creditsReserved?: number | undefined;
        /** Credit cost per profile for your team */
        creditsPerItem?: number | undefined;
        /** Estimated total credits */
        estimatedCredits?: number | undefined;
    }
}
