// This file was auto-generated by Fern from our API Definition.

export interface SuccessOperationResponse {
    success: true;
    data: SuccessOperationResponse.Data;
}

export namespace SuccessOperationResponse {
    export interface Data {
        success: boolean;
    }
}
