// This file was auto-generated by Fern from our API Definition.

export interface TeamMember {
    /** Membership ID */
    id: string;
    /** User ID */
    userId: string;
    /** The member's email address */
    email: string;
    /** The member's display name */
    name: string | null;
    /**
     * Their role in the team:
     * - `owner` — full control, cannot be removed
     * - `admin` — can manage members and keys
     * - `member` — can use the API
     */
    role: TeamMember.Role;
    /** When they joined the team */
    createdAt: string;
}

export namespace TeamMember {
    /**
     * Their role in the team:
     * - `owner` — full control, cannot be removed
     * - `admin` — can manage members and keys
     * - `member` — can use the API
     */
    export const Role = {
        Owner: "owner",
        Admin: "admin",
        Member: "member",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
}
