// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface TeamMemberListResponse {
    success: true;
    data: EnrichApi.TeamMember[];
}
