// This file was auto-generated by Fern from our API Definition.

export interface UnlockNamesResponse {
    success: true;
    data: UnlockNamesResponse.Data;
    meta?: UnlockNamesResponse.Meta | undefined;
}

export namespace UnlockNamesResponse {
    export interface Data {
        results: Data.Results.Item[];
    }

    export namespace Data {
        export type Results = Results.Item[];

        export namespace Results {
            export interface Item {
                /** Lead ID */
                id?: string | undefined;
                /** Full last name */
                lastName?: string | undefined;
            }
        }
    }

    export interface Meta {
        requestId?: string | undefined;
        creditsUsed?: number | undefined;
    }
}
