// This file was auto-generated by Fern from our API Definition.

export interface WalletBalance {
    /** Your organization ID */
    organizationId: string;
    /** Your current credit balance */
    balance: number;
    currency: "credits";
    /** When this balance was last calculated */
    asOf: string;
}
