// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

export interface WalletTransactionsResponse {
    success: true;
    data: WalletTransactionsResponse.Data;
}

export namespace WalletTransactionsResponse {
    export interface Data {
        transactions: EnrichApi.WalletTransaction[];
        pagination: EnrichApi.Pagination;
    }
}
