// This file was auto-generated by Fern from our API Definition.

export interface WalletTransaction {
    /** Transaction ID */
    id: string;
    organizationId: string;
    /** One of: `deduction`, `topup`, `adjustment`, or `refund` */
    type: string;
    /** The credit amount (negative for deductions, positive for top-ups and refunds) */
    amount: number;
    /** Your balance after this transaction */
    balanceAfter: number;
    /** A short note about what happened */
    description: string;
    /** Additional context (varies by transaction type) */
    metadata?: Record<string, unknown> | undefined;
    /** When this transaction happened */
    createdAt: string;
}
