// This file was auto-generated by Fern from our API Definition.

/**
 * Per-result callback for email finder batches.
 */
export interface WebhookEmailFinderResult {
    event: "webhook:finder_lookup.completed";
    timestamp: string;
    data: WebhookEmailFinderResult.Data;
}

export namespace WebhookEmailFinderResult {
    export interface Data {
        job_id: string;
        /** The email address that was looked up */
        result_id: string;
        result: Data.Result;
    }

    export namespace Data {
        export interface Result {
            email: string;
            result: Result.Result;
            message?: string | undefined;
            confidence?: Result.Confidence | undefined;
            is_catch_all: boolean;
            domain?: string | undefined;
            /** Email provider (GOOGLE, MICROSOFT, ZOHO, etc.) */
            provider?: string | undefined;
        }

        export namespace Result {
            export const Result = {
                Found: "found",
                NotFound: "not_found",
            } as const;
            export type Result = (typeof Result)[keyof typeof Result];
            export const Confidence = {
                High: "high",
                Medium: "medium",
                Low: "low",
            } as const;
            export type Confidence = (typeof Confidence)[keyof typeof Confidence];
        }
    }
}
