// This file was auto-generated by Fern from our API Definition.

/**
 * Per-result callback for email validation batches.
 */
export interface WebhookEmailValidationResult {
    event: "webhook:email_lookup.completed";
    timestamp: string;
    data: WebhookEmailValidationResult.Data;
}

export namespace WebhookEmailValidationResult {
    export interface Data {
        job_id: string;
        /** The email address that was validated */
        result_id: string;
        result: Data.Result;
    }

    export namespace Data {
        export interface Result {
            email: string;
            result: Result.Result;
            message?: string | undefined;
            provider?: string | undefined;
            confidence?: Result.Confidence | undefined;
            is_catch_all: boolean;
            domain?: string | undefined;
        }

        export namespace Result {
            export const Result = {
                Valid: "valid",
                Invalid: "invalid",
                Risky: "risky",
            } as const;
            export type Result = (typeof Result)[keyof typeof Result];
            export const Confidence = {
                Definitive: "definitive",
                High: "high",
                Medium: "medium",
                Low: "low",
                Temporary: "temporary",
                None: "none",
            } as const;
            export type Confidence = (typeof Confidence)[keyof typeof Confidence];
        }
    }
}
