// This file was auto-generated by Fern from our API Definition.

/**
 * Completion callback for reverse email lookup batches.
 */
export interface WebhookReverseLookupCompletion {
    event: "webhook:email_completion.completed";
    timestamp: string;
    data: WebhookReverseLookupCompletion.Data;
}

export namespace WebhookReverseLookupCompletion {
    export interface Data {
        job_id: string;
        status: string;
        total_items: number;
        found: number;
        not_found: number;
        completed_at: string;
    }
}
