// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../index.js";

/**
 * Per-result callback for reverse email lookup batches.
 */
export interface WebhookReverseLookupResult {
    event: "webhook:email_result.completed";
    timestamp: string;
    data: WebhookReverseLookupResult.Data;
}

export namespace WebhookReverseLookupResult {
    export interface Data {
        job_id: string;
        /** The email address that was looked up */
        result_id: string;
        type: Data.Type;
        /** Professional profile data (present when type is "success") */
        result?: EnrichApi.ReverseLookupResult | undefined;
        /** Error message (present when type is "error") */
        error?: string | undefined;
        /** Human-readable summary ("Person found", "No information found", or error text) */
        message?: string | undefined;
    }

    export namespace Data {
        export const Type = {
            Success: "success",
            NoMatch: "no_match",
            Error: "error",
        } as const;
        export type Type = (typeof Type)[keyof typeof Type];
    }
}
