// This file was auto-generated by Fern from our API Definition.

/**
 * Per-result callback for phone finder batches.
 */
export interface WebhookPhoneResult {
    event: "webhook:phone_result.completed";
    timestamp: string;
    data: WebhookPhoneResult.Data;
}

export namespace WebhookPhoneResult {
    export interface Data {
        job_id: string;
        /** The email or profile URL used for the lookup */
        result_id: string;
        type: Data.Type;
        /** Phone numbers found (present when type is "success") */
        phones?: string[] | undefined;
        /** Error message (present when type is "error") */
        error?: string | undefined;
        /** Human-readable summary */
        message?: string | undefined;
    }

    export namespace Data {
        export const Type = {
            Success: "success",
            NoMatch: "no_match",
            Error: "error",
        } as const;
        export type Type = (typeof Type)[keyof typeof Type];
    }
}
