// This file was auto-generated by Fern from our API Definition.

export interface WebhookCompanyFollowerCompletion {
    /** Event type identifier */
    event: string;
    /** The batch ID for this scrape job */
    batchId: string;
    /** UTC timestamp when the event was produced */
    timestamp: string;
    data: WebhookCompanyFollowerCompletion.Data;
}

export namespace WebhookCompanyFollowerCompletion {
    export interface Data {
        /** The LinkedIn company URL that was scraped */
        companyUrl: string;
        /** Total number of follower profiles scraped */
        followerCount: number;
        /** Total processing time in milliseconds */
        processingTimeMs: number;
    }
}
