// This file was auto-generated by Fern from our API Definition.

/**
 * Completion callback for email finder batches.
 */
export interface WebhookEmailFinderCompletion {
    event: "finder.completed";
    timestamp: string;
    data: WebhookEmailFinderCompletion.Data;
}

export namespace WebhookEmailFinderCompletion {
    export interface Data {
        job_id: string;
        status: "completed";
        total_items: number;
        successful: number;
        failed: number;
        completed_at: string;
        /** Number of emails successfully found */
        found?: number | undefined;
        /** Number of lookups where no email was found */
        not_found?: number | undefined;
    }
}
