// This file was auto-generated by Fern from our API Definition.

/**
 * Completion callback for email validation batches.
 */
export interface WebhookEmailValidationCompletion {
    event: "validation.completed";
    timestamp: string;
    data: WebhookEmailValidationCompletion.Data;
}

export namespace WebhookEmailValidationCompletion {
    export interface Data {
        job_id: string;
        status: "completed";
        total_items: number;
        successful: number;
        failed: number;
        completed_at: string;
        /** Number of emails that validated as valid */
        valid?: number | undefined;
        /** Number of emails that validated as invalid */
        invalid?: number | undefined;
        /** Number of emails that validated as risky */
        risky?: number | undefined;
    }
}
