// This file was auto-generated by Fern from our API Definition.

/**
 * Completion callback for phone finder batches.
 */
export interface WebhookPhoneCompletion {
    event: "webhook:phone_completion.completed";
    timestamp: string;
    data: WebhookPhoneCompletion.Data;
}

export namespace WebhookPhoneCompletion {
    export interface Data {
        job_id: string;
        status: string;
        total_items: number;
        found: number;
        not_found: number;
        completed_at: string;
    }
}
