// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as EnrichApi from "../../../index.js";

export declare namespace EmailFinderClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class EmailFinderClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<EmailFinderClient.Options>;

    constructor(options: EmailFinderClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Give us a person's first name, last name, and their company domain, and we'll
     * find their professional email address.
     *
     * **Cost:** 10 credits. You are **not** charged if we can't find an email
     * (`found: false`).
     *
     * @param {EnrichApi.EmailFinderRequest} request
     * @param {EmailFinderClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.BadRequestError}
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.PaymentRequiredError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     * @throws {@link EnrichApi.InternalServerError}
     *
     * @example
     *     await client.emailFinder.findEmail({
     *         firstName: "Emily",
     *         lastName: "Zhang",
     *         domain: "figma.com"
     *     })
     */
    public findEmail(
        request: EnrichApi.EmailFinderRequest,
        requestOptions?: EmailFinderClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.EmailFinderResponse> {
        return core.HttpResponsePromise.fromPromise(this.__findEmail(request, requestOptions));
    }

    private async __findEmail(
        request: EnrichApi.EmailFinderRequest,
        requestOptions?: EmailFinderClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.EmailFinderResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "email-finder",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as EnrichApi.EmailFinderResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new EnrichApi.BadRequestError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 402:
                    throw new EnrichApi.PaymentRequiredError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 500:
                    throw new EnrichApi.InternalServerError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/email-finder");
    }

    /**
     * Submit up to **500 000 leads** in one request. Each lead is a combination
     * of first name, last name, and domain. We deduplicate the list
     * (case-insensitive) so you are only charged for unique leads.
     *
     * **Cost:** 10 credits per unique lead, reserved at submission. Unused credits
     * are refunded when you fetch results.
     *
     * ### Webhook callbacks
     *
     * If you include a `webhookUrl`, your server will receive:
     *
     * 1. **A per-result callback** each time a single lead is processed. See
     *    [emailFinderResult](#tag/Webhooks/operation/webhookEmailFinderResult) for the payload.
     *
     * 2. **A completion callback** once the entire batch is done. See
     *    [emailFinderCompletion](#tag/Webhooks/operation/webhookEmailFinderCompletion) for the payload.
     *
     * @param {EnrichApi.BatchEmailFinderRequest} request
     * @param {EmailFinderClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.BadRequestError}
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.PaymentRequiredError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     * @throws {@link EnrichApi.InternalServerError}
     *
     * @example
     *     await client.emailFinder.batchFindEmails({
     *         leads: [{
     *                 firstName: "Emily",
     *                 lastName: "Zhang",
     *                 domain: "figma.com"
     *             }, {
     *                 firstName: "David",
     *                 lastName: "Kim",
     *                 domain: "vercel.com"
     *             }, {
     *                 firstName: "Aisha",
     *                 lastName: "Johnson",
     *                 domain: "cloudflare.com"
     *             }],
     *         webhookUrl: "https://api.yourapp.com/webhooks/enrich"
     *     })
     */
    public batchFindEmails(
        request: EnrichApi.BatchEmailFinderRequest,
        requestOptions?: EmailFinderClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.BatchSubmitResponse> {
        return core.HttpResponsePromise.fromPromise(this.__batchFindEmails(request, requestOptions));
    }

    private async __batchFindEmails(
        request: EnrichApi.BatchEmailFinderRequest,
        requestOptions?: EmailFinderClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.BatchSubmitResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "email-finder/batch",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as EnrichApi.BatchSubmitResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new EnrichApi.BadRequestError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 402:
                    throw new EnrichApi.PaymentRequiredError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 500:
                    throw new EnrichApi.InternalServerError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/email-finder/batch");
    }

    /**
     * Poll this endpoint to track your batch. The `status` moves through
     * `queued` → `processing` → `completed` (or `failed`).
     *
     * **Cost:** Free.
     *
     * @param {EnrichApi.GetEmailFinderBatchStatusRequest} request
     * @param {EmailFinderClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.NotFoundError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     *
     * @example
     *     await client.emailFinder.getEmailFinderBatchStatus({
     *         batchId: "665a1f4e2c3b7800129dce01"
     *     })
     */
    public getEmailFinderBatchStatus(
        request: EnrichApi.GetEmailFinderBatchStatusRequest,
        requestOptions?: EmailFinderClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.BatchStatusResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getEmailFinderBatchStatus(request, requestOptions));
    }

    private async __getEmailFinderBatchStatus(
        request: EnrichApi.GetEmailFinderBatchStatusRequest,
        requestOptions?: EmailFinderClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.BatchStatusResponse>> {
        const { batchId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `email-finder/batch/${core.url.encodePathParam(batchId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as EnrichApi.BatchStatusResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 404:
                    throw new EnrichApi.NotFoundError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/email-finder/batch/{batchId}");
    }

    /**
     * Retrieve the results once the batch has finished. Results are paginated.
     *
     * **Credit settlement:** On the first call after the batch reaches a terminal
     * status, we settle the final credit charge. Leads where no email was found
     * are not charged, and the difference is refunded.
     *
     * @param {EnrichApi.GetEmailFinderBatchResultsRequest} request
     * @param {EmailFinderClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.NotFoundError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     *
     * @example
     *     await client.emailFinder.getEmailFinderBatchResults({
     *         batchId: "665a1f4e2c3b7800129dce01"
     *     })
     */
    public getEmailFinderBatchResults(
        request: EnrichApi.GetEmailFinderBatchResultsRequest,
        requestOptions?: EmailFinderClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.EmailFinderBatchResultsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getEmailFinderBatchResults(request, requestOptions));
    }

    private async __getEmailFinderBatchResults(
        request: EnrichApi.GetEmailFinderBatchResultsRequest,
        requestOptions?: EmailFinderClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.EmailFinderBatchResultsResponse>> {
        const { batchId, page, limit } = request;
        const _queryParams: Record<string, unknown> = {
            page,
            limit,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `email-finder/batch/${core.url.encodePathParam(batchId)}/results`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as EnrichApi.EmailFinderBatchResultsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 404:
                    throw new EnrichApi.NotFoundError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/email-finder/batch/{batchId}/results",
        );
    }
}
