// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "665e0b2f4a6d8c001abc1234"
 *     }
 */
export interface DeleteSavedSearchRequest {
    /** Saved search ID */
    id: string;
}
