// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         leads: [{
 *                 id: "id"
 *             }],
 *         fields: ["email"]
 *     }
 */
export interface LeadEnrichRequest {
    /** Leads to enrich (max 25) */
    leads: LeadEnrichRequest.Leads.Item[];
    /** Which contact fields to reveal */
    fields: LeadEnrichRequest.Fields.Item[];
}

export namespace LeadEnrichRequest {
    export type Leads = Leads.Item[];

    export namespace Leads {
        export interface Item {
            /** Lead ID from search results */
            id: string;
        }
    }

    export type Fields = Fields.Item[];

    export namespace Fields {
        export const Item = {
            Email: "email",
            Phone: "phone",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
