// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         leads: [{
 *                 id: "enc_abc123def456"
 *             }],
 *         fields: ["email"]
 *     }
 */
export interface LeadRevealRequest {
    /** Leads to reveal (max 25) */
    leads: LeadRevealRequest.Leads.Item[];
    /** Which contact fields to reveal: 'email' (50 credits), 'phone' (525 credits), or both. Defaults to both if omitted. */
    fields?: LeadRevealRequest.Fields.Item[];
}

export namespace LeadRevealRequest {
    export type Leads = Leads.Item[];

    export namespace Leads {
        export interface Item {
            /** Lead ID from search results */
            id: string;
        }
    }

    export type Fields = Fields.Item[];

    export namespace Fields {
        export const Item = {
            Email: "email",
            Phone: "phone",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
