// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../../../../index.js";

/**
 * @example
 *     {
 *         filters: {}
 *     }
 */
export interface LeadExportRequest {
    filters: EnrichApi.LeadFinderSearchFilters;
    /** Maximum rows to export */
    maxResults?: number;
    /** Shorthand: include both email and phone (costs credits per lead) */
    includeContactInfo?: boolean;
    /** Include email addresses (50 credits per lead) */
    includeEmail?: boolean;
    /** Include phone numbers (525 credits per lead) */
    includePhone?: boolean;
    /** Include full last names (1 credit per lead) */
    includeNames?: boolean;
    /** Export specific leads by encrypted ID (selected rows mode) */
    leadIds?: string[];
    /** Export a specific page of results (current page mode) */
    page?: number;
    /** Page size when exporting a specific page */
    pageSize?: number;
}
