// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../../../../index.js";

/**
 * @example
 *     {
 *         filters: {}
 *     }
 */
export interface LeadSearchRequest {
    /** Search filters */
    filters: EnrichApi.LeadFinderSearchFilters;
    /** Page number (1–40). Pages 1–3 are free. */
    page?: number;
    /** Results per page (10–100) */
    pageSize?: number;
    /** Sort field. "none" = primary key order (fastest). Other options include field names like "lastName", "companyName", etc. */
    sortBy?: string;
    /** Sort direction */
    sortOrder?: LeadSearchRequest.SortOrder;
}

export namespace LeadSearchRequest {
    /** Sort direction */
    export const SortOrder = {
        Asc: "asc",
        Desc: "desc",
    } as const;
    export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder];
}
