// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../../../../index.js";

/**
 * @example
 *     {
 *         filters: {}
 *     }
 */
export interface LeadCountRequest {
    filters: EnrichApi.LeadFinderSearchFilters;
}
