// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "name",
 *         filters: {}
 *     }
 */
export interface SavedSearchCreateRequest {
    /** Search name */
    name: string;
    filters: EnrichApi.LeadFinderSearchFilters;
}
