// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         q: "Stri"
 *     }
 */
export interface SuggestCompanyNamesRequest {
    /** Search prefix (min 2 characters) */
    q: string;
    /** Max suggestions (1–50, default: 20) */
    limit?: number;
}
