// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         leads: [{
 *                 id: "id"
 *             }]
 *     }
 */
export interface UnlockNamesRequest {
    /** Leads whose last names to unlock (max 100) */
    leads: UnlockNamesRequest.Leads.Item[];
}

export namespace UnlockNamesRequest {
    export type Leads = Leads.Item[];

    export namespace Leads {
        export interface Item {
            /** Encrypted lead ID */
            id: string;
        }
    }
}
