// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         jobId: "665c52bf7b8e3f00149f0a10"
 *     }
 */
export interface GetPhoneBulkJobResultsRequest {
    /** The job identifier (24-character hex string) returned when you submitted the job */
    jobId: string;
    /** Page number (default: 1) */
    page?: number;
    /** Results per page (default: 100, max: 1 000) */
    limit?: number;
}
