// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         emails: ["sarah.chen@stripe.com", "james.rodriguez@hubspot.com"],
 *         linkedins: ["https://www.example.com/in/priyapatel"],
 *         webhookUrl: "https://api.yourapp.com/webhooks/enrich"
 *     }
 */
export interface PhoneBatchRequest {
    /** Email addresses to look up */
    emails?: string[];
    /** Profile URLs to look up */
    linkedins?: string[];
    /**
     * A URL on your server where we should send webhook callbacks.
     * You'll receive one POST per item, plus one final completion POST.
     */
    webhookUrl?: string;
}
