// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         email: "sarah.chen@stripe.com",
 *         linkedin: "https://www.example.com/in/sarahchen"
 *     }
 */
export interface PhoneLookupRequest {
    /** The person's email address */
    email?: string;
    /** The person's profile URL */
    linkedin?: string;
}
