// This file was auto-generated by Fern from our API Definition.

export interface EmployeeFinderResponse {
    success: boolean;
    data: EmployeeFinderResponse.Data;
    meta?: EmployeeFinderResponse.Meta | undefined;
}

export namespace EmployeeFinderResponse {
    export interface Data {
        /** The company LinkedIn URL that was searched */
        company_linkedin_url: string;
        /** Max results per page */
        max_results: number;
        /** Number of results in this page */
        results_length: number;
        /** Current page number */
        page: number;
        /** Total pages available */
        total_pages: number;
        /** Total results matching filters */
        total_results: number;
        results: Data.Results.Item[];
    }

    export namespace Data {
        export type Results = Results.Item[];

        export namespace Results {
            export interface Item {
                first_name?: (string | null) | undefined;
                last_name?: (string | null) | undefined;
                full_name?: (string | null) | undefined;
                headline?: (string | null) | undefined;
                about_me?: (string | null) | undefined;
                location?: Item.Location | undefined;
                linkedin_url?: (string | null) | undefined;
                job_title?: (string | null) | undefined;
                job_level?: (string | null) | undefined;
                job_function?: (string | null) | undefined;
                job_is_current?: boolean | undefined;
                education?: (string | null) | undefined;
                skills?: (string | null) | undefined;
                certifications?: (string | null) | undefined;
            }

            export namespace Item {
                export interface Location {
                    city?: (string | null) | undefined;
                    state_code?: (string | null) | undefined;
                    country?: (string | null) | undefined;
                    country_code?: (string | null) | undefined;
                    continent?: (string | null) | undefined;
                }
            }
        }
    }

    export interface Meta {
        requestId?: string | undefined;
        /** Credits charged (1 per result returned, 0 if no results) */
        creditsUsed?: number | undefined;
        /** Remaining credit balance */
        creditsRemaining?: number | undefined;
    }
}
