// This file was auto-generated by Fern from our API Definition.

export interface WaterfallIcpSearchResponse {
    success: boolean;
    data: WaterfallIcpSearchResponse.Data;
    meta: WaterfallIcpSearchResponse.Meta;
}

export namespace WaterfallIcpSearchResponse {
    export interface Data {
        /** Ranked list of matching candidates sorted by ICP score descending */
        results: Data.Results.Item[];
        /** Total candidates found across all cascade levels (before min_score filtering) */
        total_found: number;
        /** Number of results actually returned after filtering and max_results cap */
        total_returned: number;
        /** Per-cascade-level statistics showing how many candidates were found and kept */
        cascade_stats: Data.CascadeStats.Item[];
    }

    export namespace Data {
        export type Results = Results.Item[];

        export namespace Results {
            export interface Item {
                /** Person identifying information */
                person: Item.Person;
                /** Current job position details */
                current_position: Item.CurrentPosition;
                /** Parsed skills list from candidate profile */
                skills: string[];
                education: string | null;
                certifications: string | null;
                /** Normalized ICP score (0-100). Normalized against only the scoring dimensions that were specified in the cascade level. */
                score: number;
                /** Rank position (1-based, sorted by score descending) */
                ranking: number;
                /** Which cascade level matched this candidate (0-based index) */
                cascade_level: number;
                /** Breakdown of raw points awarded for each scoring dimension */
                ranking_factors: Item.RankingFactors;
                /** Human-readable list of matching criteria for this candidate */
                what_matched: string[];
            }

            export namespace Item {
                /**
                 * Person identifying information
                 */
                export interface Person {
                    first_name?: (string | null) | undefined;
                    last_name?: (string | null) | undefined;
                    linkedin_url?: (string | null) | undefined;
                    linkedin_headline?: (string | null) | undefined;
                    /** Concatenation of city, state, and country */
                    location?: (string | null) | undefined;
                    email_domain?: (string | null) | undefined;
                }

                /**
                 * Current job position details
                 */
                export interface CurrentPosition {
                    title?: (string | null) | undefined;
                    company?: (string | null) | undefined;
                    level?: (string | null) | undefined;
                    function?: (string | null) | undefined;
                    is_current?: (boolean | null) | undefined;
                    /** Job start date in YYYY-MM-DD format */
                    start_date?: (string | null) | undefined;
                }

                /**
                 * Breakdown of raw points awarded for each scoring dimension
                 */
                export interface RankingFactors {
                    /** Points from title matching (max 30). 30=exact, 25=partial/substring, 20=headline, 10=function match */
                    title_match?: number | undefined;
                    /** Points from job level matching (max 20). 20=exact, 10=adjacent ±1, 5=near ±2 */
                    job_level?: number | undefined;
                    /** Points from skills overlap (max 15). Calculated as (matched/requested) * 15 */
                    skills_overlap?: number | undefined;
                    /** Points from location matching (max 15). 15=country/WORLD, 7=continent */
                    location_match?: number | undefined;
                    /** Points from current job status (max 10). 10 if JOB_IS_CURRENT_PER is true */
                    current_job?: number | undefined;
                    /** Points from profile completeness (max 5). 1 point each for: linkedin_url, email_domain, skills, education, headline */
                    profile_completeness?: number | undefined;
                    /** Points from job tenure (max 5). 5=>5yr, 4=>3yr, 3=>2yr, 2=>1yr, 1=≤1yr */
                    experience?: number | undefined;
                    /** Seniority priority bonus from cascade level (0-30). Higher = ranked above other cascade levels at equal match quality */
                    priority_bonus?: number | undefined;
                }
            }
        }

        export type CascadeStats = CascadeStats.Item[];

        export namespace CascadeStats {
            export interface Item {
                /** Cascade level index (0-based) */
                level: number;
                /** Total candidates returned from ClickHouse for this level */
                candidates_found: number;
                /** Candidates that passed min_score and deduplication */
                candidates_kept: number;
            }
        }
    }

    export interface Meta {
        requestId?: string | undefined;
        /** Credits charged for this request (1 per profile returned, 0 if no results) */
        creditsUsed?: number | undefined;
        /** Remaining credit balance after this request */
        creditsRemaining?: number | undefined;
    }
}
