// This file was auto-generated by Fern from our API Definition.

import type * as EnrichApi from "../../../../index.js";

/**
 * @example
 *     {
 *         leads: [{
 *                 firstName: "Emily",
 *                 lastName: "Zhang",
 *                 domain: "figma.com"
 *             }, {
 *                 firstName: "David",
 *                 lastName: "Kim",
 *                 domain: "vercel.com"
 *             }, {
 *                 firstName: "Aisha",
 *                 lastName: "Johnson",
 *                 domain: "cloudflare.com"
 *             }],
 *         webhookUrl: "https://api.yourapp.com/webhooks/enrich"
 *     }
 */
export interface BatchEmailFinderRequest {
    /** The list of people to search for (up to 500 000) */
    leads: EnrichApi.Lead[];
    /**
     * A URL on your server where we should send webhook callbacks.
     * You'll receive one POST per lead, plus one final completion POST.
     */
    webhookUrl?: string;
}
