// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         firstName: "Emily",
 *         lastName: "Zhang",
 *         domain: "figma.com"
 *     }
 */
export interface EmailFinderRequest {
    /** The person's first name */
    firstName: string;
    /** The person's last name */
    lastName: string;
    /** The company domain to search (e.g. `figma.com`) */
    domain: string;
}
