// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         batchId: "665a1f4e2c3b7800129dce01"
 *     }
 */
export interface GetEmailFinderBatchResultsRequest {
    /** The batch identifier returned when you submitted the job */
    batchId: string;
    /** Page number (default: 1) */
    page?: number;
    /** Results per page (default: 100, max: 1 000) */
    limit?: number;
}
