// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         teamId: "665e0b2f4a6d8c001abc1234",
 *         invitationId: "665e2e7f4a6d8c001abc5001"
 *     }
 */
export interface CancelInvitationRequest {
    /** Your team identifier */
    teamId: string;
    /** The invitation identifier */
    invitationId: string;
}
