// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         teamId: "665e0b2f4a6d8c001abc1234",
 *         email: "marco.silva@yourcompany.com",
 *         role: "member"
 *     }
 */
export interface InviteBody {
    /** Your team identifier */
    teamId: string;
    /** The email address of the person you want to invite */
    email: string;
    /** The role to assign them */
    role: InviteBody.Role;
}

export namespace InviteBody {
    /** The role to assign them */
    export const Role = {
        Admin: "admin",
        Member: "member",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
}
