// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         teamId: "665e0b2f4a6d8c001abc1234"
 *     }
 */
export interface ListTeamMembersRequest {
    /** Your team identifier */
    teamId: string;
}
