// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as EnrichApi from "../../../index.js";

export declare namespace EmailValidationClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class EmailValidationClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<EmailValidationClient.Options>;

    constructor(options: EmailValidationClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Checks whether an email address is deliverable. The response tells you the
     * result (`valid`, `invalid`, or `risky`), the confidence level, the mail
     * provider, and whether the domain is a catch-all.
     *
     * **Cost:** 1 credit. You are **not** charged if the result is `risky`.
     *
     * @param {EnrichApi.EmailValidationRequest} request
     * @param {EmailValidationClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.BadRequestError}
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.PaymentRequiredError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     * @throws {@link EnrichApi.InternalServerError}
     *
     * @example
     *     await client.emailValidation.validateEmail({
     *         email: "sarah.chen@stripe.com"
     *     })
     */
    public validateEmail(
        request: EnrichApi.EmailValidationRequest,
        requestOptions?: EmailValidationClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.EmailValidationResponse> {
        return core.HttpResponsePromise.fromPromise(this.__validateEmail(request, requestOptions));
    }

    private async __validateEmail(
        request: EnrichApi.EmailValidationRequest,
        requestOptions?: EmailValidationClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.EmailValidationResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "email-validation",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as EnrichApi.EmailValidationResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new EnrichApi.BadRequestError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 402:
                    throw new EnrichApi.PaymentRequiredError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 500:
                    throw new EnrichApi.InternalServerError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/email-validation");
    }

    /**
     * Submit up to **500 000 emails** in a single request. We automatically
     * remove duplicates (case-insensitive) before processing, so you only pay
     * for unique addresses.
     *
     * **Cost:** 1 credit per unique email, reserved when you submit. Any unused
     * credits are refunded automatically when you fetch results.
     *
     * ### Webhook callbacks
     *
     * If you include a `webhookUrl`, your server will receive:
     *
     * 1. **A per-result callback** every time an individual email finishes
     *    validation. See [emailValidationResult](#tag/Webhooks/operation/webhookEmailValidationResult)
     *    for the exact payload.
     *
     * 2. **A completion callback** once every email in the batch has been
     *    processed. See [emailValidationCompletion](#tag/Webhooks/operation/webhookEmailValidationCompletion)
     *    for the exact payload.
     *
     * @param {EnrichApi.BatchEmailValidationRequest} request
     * @param {EmailValidationClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.BadRequestError}
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.PaymentRequiredError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     * @throws {@link EnrichApi.InternalServerError}
     *
     * @example
     *     await client.emailValidation.batchValidateEmails({
     *         emails: ["sarah.chen@stripe.com", "james.rodriguez@hubspot.com", "priya.patel@notion.so", "marco.silva@datadog.com"],
     *         webhookUrl: "https://api.yourapp.com/webhooks/enrich"
     *     })
     */
    public batchValidateEmails(
        request: EnrichApi.BatchEmailValidationRequest,
        requestOptions?: EmailValidationClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.BatchSubmitResponse> {
        return core.HttpResponsePromise.fromPromise(this.__batchValidateEmails(request, requestOptions));
    }

    private async __batchValidateEmails(
        request: EnrichApi.BatchEmailValidationRequest,
        requestOptions?: EmailValidationClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.BatchSubmitResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "email-validation/batch",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as EnrichApi.BatchSubmitResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new EnrichApi.BadRequestError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 402:
                    throw new EnrichApi.PaymentRequiredError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 500:
                    throw new EnrichApi.InternalServerError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/email-validation/batch");
    }

    /**
     * Poll this endpoint to see how your batch is doing. The `progress` field
     * gives you a percentage, and `status` will be one of `queued`, `processing`,
     * `completed`, or `failed`.
     *
     * **Cost:** Free — polling never costs credits.
     *
     * @param {EnrichApi.GetEmailValidationBatchStatusRequest} request
     * @param {EmailValidationClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.NotFoundError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     *
     * @example
     *     await client.emailValidation.getEmailValidationBatchStatus({
     *         batchId: "665a1f4e2c3b7800129dce01"
     *     })
     */
    public getEmailValidationBatchStatus(
        request: EnrichApi.GetEmailValidationBatchStatusRequest,
        requestOptions?: EmailValidationClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.BatchStatusResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getEmailValidationBatchStatus(request, requestOptions));
    }

    private async __getEmailValidationBatchStatus(
        request: EnrichApi.GetEmailValidationBatchStatusRequest,
        requestOptions?: EmailValidationClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.BatchStatusResponse>> {
        const { batchId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `email-validation/batch/${core.url.encodePathParam(batchId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as EnrichApi.BatchStatusResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 404:
                    throw new EnrichApi.NotFoundError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/email-validation/batch/{batchId}",
        );
    }

    /**
     * Fetch the results once your batch has finished. Results are paginated — use
     * `page` and `limit` to walk through them.
     *
     * **Credit settlement:** The first time you call this after the batch reaches
     * `completed` or `failed`, we calculate the final cost and refund any excess
     * credits. Subsequent calls return the cached settlement.
     *
     * @param {EnrichApi.GetEmailValidationBatchResultsRequest} request
     * @param {EmailValidationClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.NotFoundError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     *
     * @example
     *     await client.emailValidation.getEmailValidationBatchResults({
     *         batchId: "665a1f4e2c3b7800129dce01"
     *     })
     */
    public getEmailValidationBatchResults(
        request: EnrichApi.GetEmailValidationBatchResultsRequest,
        requestOptions?: EmailValidationClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.EmailValidationBatchResultsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getEmailValidationBatchResults(request, requestOptions));
    }

    private async __getEmailValidationBatchResults(
        request: EnrichApi.GetEmailValidationBatchResultsRequest,
        requestOptions?: EmailValidationClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.EmailValidationBatchResultsResponse>> {
        const { batchId, page, limit } = request;
        const _queryParams: Record<string, unknown> = {
            page,
            limit,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `email-validation/batch/${core.url.encodePathParam(batchId)}/results`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as EnrichApi.EmailValidationBatchResultsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 404:
                    throw new EnrichApi.NotFoundError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/email-validation/batch/{batchId}/results",
        );
    }
}
