// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         batchId: "batchId"
 *     }
 */
export interface ExportCompanyFollowerCsvRequest {
    /** The batch identifier returned when you started the scrape */
    batchId: string;
}
