// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         batchId: "665a1f4e2c3b7800129dce01"
 *     }
 */
export interface GetCompanyFollowerProgressRequest {
    /** The batch identifier returned when you started the scrape */
    batchId: string;
}
