// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         batchId: "665a1f4e2c3b7800129dce01"
 *     }
 */
export interface GetCompanyFollowerResultsRequest {
    /** The batch identifier returned when you started the scrape */
    batchId: string;
    /** Page number (default: 1) */
    page?: number;
    /** Results per page, max 500 (default: 100) */
    limit?: number;
}
