// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         batchId: "665b2a3f4c5d6e0013fgh002"
 *     }
 */
export interface GetCountEstimateStatusRequest {
    /** The batch identifier returned when you started the estimation */
    batchId: string;
}
