// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetWalletTransactionsRequest {
    /** Page number (default: 1) */
    page?: number;
    /** Items per page (default: 50, max: 100) */
    limit?: number;
    /** Filter by type: `deduction`, `topup`, `adjustment`, or `refund` */
    type?: string;
}
