// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as EnrichApi from "../../../index.js";

export declare namespace LeadFinderClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class LeadFinderClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<LeadFinderClient.Options>;

    constructor(options: LeadFinderClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Search across people, companies, and insights dimensions with comprehensive filters. Returns combined person + org + insights data.
     *
     * **Free tier:**
     * - First 75 results free (pages 1–3 at default page size of 25)
     * - 50 free search queries per month
     *
     * **Paid tier (page 4+):**
     * - 1 credit per result returned
     * - Max 40 pages
     *
     * Results include preview fields only. Use the **Reveal** or **Enrich** endpoints to get email and phone.
     *
     * **Requires approved Lead Finder access.** Returns 403 if your team has not been approved.
     *
     * @param {EnrichApi.LeadSearchRequest} request
     * @param {LeadFinderClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.BadRequestError}
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.PaymentRequiredError}
     * @throws {@link EnrichApi.ForbiddenError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     * @throws {@link EnrichApi.InternalServerError}
     *
     * @example
     *     await client.leadFinder.searchLeads({
     *         filters: {}
     *     })
     */
    public searchLeads(
        request: EnrichApi.LeadSearchRequest,
        requestOptions?: LeadFinderClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.LeadSearchResponse> {
        return core.HttpResponsePromise.fromPromise(this.__searchLeads(request, requestOptions));
    }

    private async __searchLeads(
        request: EnrichApi.LeadSearchRequest,
        requestOptions?: LeadFinderClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.LeadSearchResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "lead-finder/search",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as EnrichApi.LeadSearchResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new EnrichApi.BadRequestError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 402:
                    throw new EnrichApi.PaymentRequiredError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 403:
                    throw new EnrichApi.ForbiddenError(
                        _response.error.body as EnrichApi.AccessDeniedResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 500:
                    throw new EnrichApi.InternalServerError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/lead-finder/search");
    }

    /**
     * Get the total count of leads matching your filters. This endpoint is free and does not consume credits.
     *
     * **Requires approved Lead Finder access.** Returns 403 if your team has not been approved.
     *
     * @param {EnrichApi.LeadCountRequest} request
     * @param {LeadFinderClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.BadRequestError}
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.ForbiddenError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     * @throws {@link EnrichApi.InternalServerError}
     *
     * @example
     *     await client.leadFinder.countLeads({
     *         filters: {}
     *     })
     */
    public countLeads(
        request: EnrichApi.LeadCountRequest,
        requestOptions?: LeadFinderClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.LeadCountResponse> {
        return core.HttpResponsePromise.fromPromise(this.__countLeads(request, requestOptions));
    }

    private async __countLeads(
        request: EnrichApi.LeadCountRequest,
        requestOptions?: LeadFinderClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.LeadCountResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "lead-finder/count",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as EnrichApi.LeadCountResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new EnrichApi.BadRequestError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 403:
                    throw new EnrichApi.ForbiddenError(
                        _response.error.body as EnrichApi.AccessDeniedResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 500:
                    throw new EnrichApi.InternalServerError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/lead-finder/count");
    }

    /**
     * Export search results as a CSV file.
     *
     * **Pricing:**
     * - Preview fields only: Free
     * - `includeEmail`: 50 credits per lead
     * - `includePhone`: 525 credits per lead
     * - `includeNames`: 1 credit per lead (full last names)
     * - `includeContactInfo`: Shorthand for email + phone (575 credits/lead)
     *
     * Previously revealed contacts are returned from cache at no additional cost. Credits are refunded for leads where contact info is unavailable.
     *
     * **Response:** Returns a CSV file (Content-Type: text/csv) with `X-Credits-Used` and `X-Credits-Refunded` headers.
     *
     * **Requires approved Lead Finder access.** Returns 403 if your team has not been approved.
     *
     * @param {EnrichApi.LeadExportRequest} request
     * @param {LeadFinderClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.BadRequestError}
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.PaymentRequiredError}
     * @throws {@link EnrichApi.ForbiddenError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     * @throws {@link EnrichApi.InternalServerError}
     *
     * @example
     *     await client.leadFinder.exportLeads({
     *         filters: {}
     *     })
     */
    public exportLeads(
        request: EnrichApi.LeadExportRequest,
        requestOptions?: LeadFinderClient.RequestOptions,
    ): core.HttpResponsePromise<string> {
        return core.HttpResponsePromise.fromPromise(this.__exportLeads(request, requestOptions));
    }

    private async __exportLeads(
        request: EnrichApi.LeadExportRequest,
        requestOptions?: LeadFinderClient.RequestOptions,
    ): Promise<core.WithRawResponse<string>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "lead-finder/export",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            responseType: "text",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as string, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new EnrichApi.BadRequestError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 402:
                    throw new EnrichApi.PaymentRequiredError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 403:
                    throw new EnrichApi.ForbiddenError(
                        _response.error.body as EnrichApi.AccessDeniedResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 500:
                    throw new EnrichApi.InternalServerError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/lead-finder/export");
    }

    /**
     * Reveal contact info for up to 25 leads. Choose which fields to reveal via the optional `fields` parameter:
     *
     * - `["email"]` — 50 credits per lead
     * - `["phone"]` — 525 credits per lead
     * - `["email", "phone"]` — 575 credits per lead (default if omitted)
     *
     * Previously revealed contacts are returned from cache at no cost. Returns 402 if insufficient credits.
     *
     * **Requires approved Lead Finder access.** Returns 403 if your team has not been approved.
     *
     * @param {EnrichApi.LeadRevealRequest} request
     * @param {LeadFinderClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.BadRequestError}
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.PaymentRequiredError}
     * @throws {@link EnrichApi.ForbiddenError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     * @throws {@link EnrichApi.InternalServerError}
     *
     * @example
     *     await client.leadFinder.revealLeads({
     *         leads: [{
     *                 id: "enc_abc123def456"
     *             }],
     *         fields: ["email"]
     *     })
     */
    public revealLeads(
        request: EnrichApi.LeadRevealRequest,
        requestOptions?: LeadFinderClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.LeadRevealResponse> {
        return core.HttpResponsePromise.fromPromise(this.__revealLeads(request, requestOptions));
    }

    private async __revealLeads(
        request: EnrichApi.LeadRevealRequest,
        requestOptions?: LeadFinderClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.LeadRevealResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "lead-finder/reveal",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as EnrichApi.LeadRevealResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new EnrichApi.BadRequestError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 402:
                    throw new EnrichApi.PaymentRequiredError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 403:
                    throw new EnrichApi.ForbiddenError(
                        _response.error.body as EnrichApi.AccessDeniedResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 500:
                    throw new EnrichApi.InternalServerError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/lead-finder/reveal");
    }

    /**
     * Reveal specific contact fields (email and/or phone) for up to 25 leads.
     *
     * **Pricing:**
     * - Email: 50 credits per lead
     * - Phone: 525 credits per lead
     *
     * Previously revealed fields are returned from cache at no cost.
     *
     * **Requires approved Lead Finder access.** Returns 403 if your team has not been approved.
     *
     * @param {EnrichApi.LeadEnrichRequest} request
     * @param {LeadFinderClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.BadRequestError}
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.PaymentRequiredError}
     * @throws {@link EnrichApi.ForbiddenError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     * @throws {@link EnrichApi.InternalServerError}
     *
     * @example
     *     await client.leadFinder.enrichLeads({
     *         leads: [{
     *                 id: "id"
     *             }],
     *         fields: ["email"]
     *     })
     */
    public enrichLeads(
        request: EnrichApi.LeadEnrichRequest,
        requestOptions?: LeadFinderClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.LeadEnrichResponse> {
        return core.HttpResponsePromise.fromPromise(this.__enrichLeads(request, requestOptions));
    }

    private async __enrichLeads(
        request: EnrichApi.LeadEnrichRequest,
        requestOptions?: LeadFinderClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.LeadEnrichResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "lead-finder/enrich",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as EnrichApi.LeadEnrichResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new EnrichApi.BadRequestError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 402:
                    throw new EnrichApi.PaymentRequiredError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 403:
                    throw new EnrichApi.ForbiddenError(
                        _response.error.body as EnrichApi.AccessDeniedResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 500:
                    throw new EnrichApi.InternalServerError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/lead-finder/enrich");
    }

    /**
     * Pay 1 credit per lead to unlock full last names. Search results mask last names by default; this endpoint reveals them.
     *
     * **Requires approved Lead Finder access.** Returns 403 if your team has not been approved.
     *
     * @param {EnrichApi.UnlockNamesRequest} request
     * @param {LeadFinderClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.BadRequestError}
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.PaymentRequiredError}
     * @throws {@link EnrichApi.ForbiddenError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     * @throws {@link EnrichApi.InternalServerError}
     *
     * @example
     *     await client.leadFinder.unlockNames({
     *         leads: [{
     *                 id: "id"
     *             }]
     *     })
     */
    public unlockNames(
        request: EnrichApi.UnlockNamesRequest,
        requestOptions?: LeadFinderClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.UnlockNamesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__unlockNames(request, requestOptions));
    }

    private async __unlockNames(
        request: EnrichApi.UnlockNamesRequest,
        requestOptions?: LeadFinderClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.UnlockNamesResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "lead-finder/unlock-names",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as EnrichApi.UnlockNamesResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new EnrichApi.BadRequestError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 402:
                    throw new EnrichApi.PaymentRequiredError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 403:
                    throw new EnrichApi.ForbiddenError(
                        _response.error.body as EnrichApi.AccessDeniedResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 500:
                    throw new EnrichApi.InternalServerError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/lead-finder/unlock-names");
    }

    /**
     * List all saved searches for the current user. Free endpoint.
     *
     * **Requires approved Lead Finder access.** Returns 403 if your team has not been approved.
     *
     * @param {LeadFinderClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.BadRequestError}
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.ForbiddenError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     * @throws {@link EnrichApi.InternalServerError}
     *
     * @example
     *     await client.leadFinder.listSavedSearches()
     */
    public listSavedSearches(
        requestOptions?: LeadFinderClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.SavedSearchListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listSavedSearches(requestOptions));
    }

    private async __listSavedSearches(
        requestOptions?: LeadFinderClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.SavedSearchListResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "lead-finder/saved",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as EnrichApi.SavedSearchListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new EnrichApi.BadRequestError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 403:
                    throw new EnrichApi.ForbiddenError(
                        _response.error.body as EnrichApi.AccessDeniedResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 500:
                    throw new EnrichApi.InternalServerError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/lead-finder/saved");
    }

    /**
     * Save a search filter combination for reuse. Free endpoint.
     *
     * **Requires approved Lead Finder access.** Returns 403 if your team has not been approved.
     *
     * @param {EnrichApi.SavedSearchCreateRequest} request
     * @param {LeadFinderClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.BadRequestError}
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.ForbiddenError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     * @throws {@link EnrichApi.InternalServerError}
     *
     * @example
     *     await client.leadFinder.createSavedSearch({
     *         name: "name",
     *         filters: {}
     *     })
     */
    public createSavedSearch(
        request: EnrichApi.SavedSearchCreateRequest,
        requestOptions?: LeadFinderClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.SavedSearchResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createSavedSearch(request, requestOptions));
    }

    private async __createSavedSearch(
        request: EnrichApi.SavedSearchCreateRequest,
        requestOptions?: LeadFinderClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.SavedSearchResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "lead-finder/saved",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as EnrichApi.SavedSearchResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new EnrichApi.BadRequestError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 403:
                    throw new EnrichApi.ForbiddenError(
                        _response.error.body as EnrichApi.AccessDeniedResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 500:
                    throw new EnrichApi.InternalServerError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/lead-finder/saved");
    }

    /**
     * Delete a saved search by ID. Only the owner can delete their own saved searches.
     *
     * **Requires approved Lead Finder access.** Returns 403 if your team has not been approved.
     *
     * @param {EnrichApi.DeleteSavedSearchRequest} request
     * @param {LeadFinderClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.BadRequestError}
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.ForbiddenError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     * @throws {@link EnrichApi.InternalServerError}
     *
     * @example
     *     await client.leadFinder.deleteSavedSearch({
     *         id: "665e0b2f4a6d8c001abc1234"
     *     })
     */
    public deleteSavedSearch(
        request: EnrichApi.DeleteSavedSearchRequest,
        requestOptions?: LeadFinderClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.LeadFinderDeletedResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deleteSavedSearch(request, requestOptions));
    }

    private async __deleteSavedSearch(
        request: EnrichApi.DeleteSavedSearchRequest,
        requestOptions?: LeadFinderClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.LeadFinderDeletedResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `lead-finder/saved/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as EnrichApi.LeadFinderDeletedResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new EnrichApi.BadRequestError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 403:
                    throw new EnrichApi.ForbiddenError(
                        _response.error.body as EnrichApi.AccessDeniedResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 500:
                    throw new EnrichApi.InternalServerError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/lead-finder/saved/{id}");
    }

    /**
     * Returns available values for multi-select filter fields (countries, departments, industries, job functions, etc.). Values are fetched from the database and cached for performance. Free endpoint.
     *
     * **Requires approved Lead Finder access.** Returns 403 if your team has not been approved.
     *
     * @param {LeadFinderClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.BadRequestError}
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.ForbiddenError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     * @throws {@link EnrichApi.InternalServerError}
     *
     * @example
     *     await client.leadFinder.getFilterOptions()
     */
    public getFilterOptions(
        requestOptions?: LeadFinderClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.LeadFinderFilterOptionsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getFilterOptions(requestOptions));
    }

    private async __getFilterOptions(
        requestOptions?: LeadFinderClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.LeadFinderFilterOptionsResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "lead-finder/filter-options",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as EnrichApi.LeadFinderFilterOptionsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new EnrichApi.BadRequestError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 403:
                    throw new EnrichApi.ForbiddenError(
                        _response.error.body as EnrichApi.AccessDeniedResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 500:
                    throw new EnrichApi.InternalServerError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/lead-finder/filter-options");
    }

    /**
     * Prefix-based company name autocomplete. Returns matching company names for search typeahead. Free endpoint.
     *
     * **Requires approved Lead Finder access.** Returns 403 if your team has not been approved.
     *
     * @param {EnrichApi.SuggestCompanyNamesRequest} request
     * @param {LeadFinderClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.BadRequestError}
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.ForbiddenError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     * @throws {@link EnrichApi.InternalServerError}
     *
     * @example
     *     await client.leadFinder.suggestCompanyNames({
     *         q: "Stri"
     *     })
     */
    public suggestCompanyNames(
        request: EnrichApi.SuggestCompanyNamesRequest,
        requestOptions?: LeadFinderClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.LeadFinderSuggestResponse> {
        return core.HttpResponsePromise.fromPromise(this.__suggestCompanyNames(request, requestOptions));
    }

    private async __suggestCompanyNames(
        request: EnrichApi.SuggestCompanyNamesRequest,
        requestOptions?: LeadFinderClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.LeadFinderSuggestResponse>> {
        const { q, limit } = request;
        const _queryParams: Record<string, unknown> = {
            q,
            limit,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "lead-finder/suggest",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as EnrichApi.LeadFinderSuggestResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new EnrichApi.BadRequestError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 403:
                    throw new EnrichApi.ForbiddenError(
                        _response.error.body as EnrichApi.AccessDeniedResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 500:
                    throw new EnrichApi.InternalServerError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/lead-finder/suggest");
    }
}
