// This file was auto-generated by Fern from our API Definition.

export interface CheckCompanyFollowerLimitResponse {
    success: boolean;
    data: CheckCompanyFollowerLimitResponse.Data;
    meta?: CheckCompanyFollowerLimitResponse.Meta | undefined;
}

export namespace CheckCompanyFollowerLimitResponse {
    export interface Data {
        /** Access status: approved, pending, rejected, revoked, or none */
        status: string;
        /** Maximum profiles allowed per day */
        dailyLimit?: number | undefined;
        /** Profiles used today */
        dailyUsed?: number | undefined;
        /** Profiles remaining today */
        dailyRemaining?: number | undefined;
        /** Credit cost per follower profile for your team */
        creditsPerProfile?: number | undefined;
    }

    export interface Meta {
        requestId?: string | undefined;
    }
}
