// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         company_linkedin_url: "https://www.linkedin.com/company/google/"
 *     }
 */
export interface EmployeeFinderRequest {
    /** LinkedIn company profile URL (required). Must be a valid LinkedIn company URL. */
    company_linkedin_url: string;
    /** Country names to filter (e.g. "India", "United States", "Germany") */
    country?: string[];
    /** Continent filter */
    continent?: string[];
    /** Sales region filter */
    sales_region?: string[];
    /** Job level/seniority filter */
    job_level?: string[];
    /** Job function/department filter */
    job_function?: string[];
    /** Results per page (1-100, default 10) */
    max_results?: number;
    /** Page number (starts at 1) */
    page?: number;
}
