// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         company_linkedin_url: "https://www.linkedin.com/company/google/"
 *     }
 *
 * @example
 *     {
 *         company_linkedin_url: "https://www.linkedin.com/company/google/"
 *     }
 */
export interface WaterfallIcpSearchRequest {
    /** Company LinkedIn URL to search employees for. Must be a valid LinkedIn company URL. */
    company_linkedin_url: string;
    /** Cascading ICP filter levels, processed in order. Results from earlier levels are excluded from later ones (deduplication by RBID_PER). If omitted, uses a default 4-level cascade: CEO/Founder → C-Suite → VP → Director. */
    cascade?: WaterfallIcpSearchRequest.Cascade.Item[];
    /** Maximum total results to return across all cascade levels */
    max_results?: number;
    /** Minimum ICP score threshold (0-100). Candidates scoring below this are filtered out. */
    min_score?: number;
}

export namespace WaterfallIcpSearchRequest {
    export type Cascade = Cascade.Item[];

    export namespace Cascade {
        export interface Item {
            /** Job titles to include (case-insensitive exact match or headline search) */
            include_title?: string[] | undefined;
            /** Job titles to exclude (case-insensitive) */
            exclude_title?: string[] | undefined;
            /** Job seniority levels to filter (e.g. Owner, Founder, C-Level, Partner, VP, Director, Manager, Senior, Staff, Entry, Intern) */
            job_levels?: string[] | undefined;
            /** Job function areas to filter (e.g. Engineering, Marketing, Sales, Technology) */
            job_functions?: string[] | undefined;
            /** Skills to match against candidate profiles (fuzzy substring matching) */
            skills?: string[] | undefined;
            /** Location codes: ISO 3166-1 alpha-2 country codes (US, UK, DE, etc.), continent codes (NORTH_AMERICA, EUROPE, ASIA, etc.), or "WORLD" for any location */
            location?: string[] | undefined;
            /** When true, also search LinkedIn headline for include_title terms (in addition to job title) */
            include_headline_search?: boolean | undefined;
            /** Seniority priority bonus (0-30). Higher = ranked above other cascade levels at equal match quality */
            priority_bonus?: number | undefined;
        }
    }
}
