// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         emails: ["sarah.chen@stripe.com", "james.rodriguez@hubspot.com", "priya.patel@notion.so", "marco.silva@datadog.com"],
 *         webhookUrl: "https://api.yourapp.com/webhooks/enrich"
 *     }
 */
export interface BatchEmailValidationRequest {
    /** A list of email addresses to validate (up to 500 000) */
    emails: string[];
    /**
     * A URL on your server where we should send webhook callbacks.
     * You'll receive one POST per result, plus one final completion POST.
     */
    webhookUrl?: string;
}
