// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         email: "sarah.chen@stripe.com"
 *     }
 */
export interface EmailValidationRequest {
    /** The email address you want to validate */
    email: string;
}
