// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as EnrichApi from "../../../index.js";

export declare namespace CompanyFollowersClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class CompanyFollowersClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<CompanyFollowersClient.Options>;

    constructor(options: CompanyFollowersClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * > **Access required** — This endpoint is available to approved accounts only. [Contact us](https://enrich.so) to request access.
     *
     * Starts an asynchronous count estimation job. Returns the estimated number of followers matching your filters, with optional breakdowns by department and seniority.
     *
     * **Cost:** 100 credits (fixed). Cached results for the same company + filters within 24 hours are free.
     *
     * **Results:** Poll the status endpoint to get results. Typically completes within 30–60 seconds.
     *
     * @param {EnrichApi.CountEstimateRequest} request
     * @param {CompanyFollowersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.BadRequestError}
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.PaymentRequiredError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     * @throws {@link EnrichApi.InternalServerError}
     *
     * @example
     *     await client.companyFollowers.startCountEstimate({
     *         companyUrl: "https://linkedin.com/company/stripe",
     *         departments: ["Engineering", "Sales"]
     *     })
     */
    public startCountEstimate(
        request: EnrichApi.CountEstimateRequest,
        requestOptions?: CompanyFollowersClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.StartCountEstimateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__startCountEstimate(request, requestOptions));
    }

    private async __startCountEstimate(
        request: EnrichApi.CountEstimateRequest,
        requestOptions?: CompanyFollowersClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.StartCountEstimateResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "count-estimate",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as EnrichApi.StartCountEstimateResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new EnrichApi.BadRequestError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 402:
                    throw new EnrichApi.PaymentRequiredError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 500:
                    throw new EnrichApi.InternalServerError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/count-estimate");
    }

    /**
     * > **Access required** — This endpoint is available to approved accounts only. [Contact us](https://enrich.so) to request access.
     *
     * Check the status of a count estimation job and retrieve results when complete.
     *
     * **Cost:** Free — polling never costs credits.
     *
     * **Refunds:** If the job fails within 7 days, the 100 credits are refunded automatically on the next status check.
     *
     * @param {EnrichApi.GetCountEstimateStatusRequest} request
     * @param {CompanyFollowersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.NotFoundError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     *
     * @example
     *     await client.companyFollowers.getCountEstimateStatus({
     *         batchId: "665b2a3f4c5d6e0013fgh002"
     *     })
     */
    public getCountEstimateStatus(
        request: EnrichApi.GetCountEstimateStatusRequest,
        requestOptions?: CompanyFollowersClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.CountEstimateStatusResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getCountEstimateStatus(request, requestOptions));
    }

    private async __getCountEstimateStatus(
        request: EnrichApi.GetCountEstimateStatusRequest,
        requestOptions?: CompanyFollowersClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.CountEstimateStatusResponse>> {
        const { batchId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `count-estimate/${core.url.encodePathParam(batchId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as EnrichApi.CountEstimateStatusResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 404:
                    throw new EnrichApi.NotFoundError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/count-estimate/{batchId}");
    }

    /**
     * > **Access required** — This endpoint is available to approved accounts only. [Contact us](https://enrich.so) to request access.
     *
     * Starts an asynchronous company follower scrape. Provide a company URL and a max_limit for how many profiles to retrieve.
     *
     * **Cost:** Credits per profile (see the /limit endpoint for your team's rate), reserved upfront based on max_limit. When you fetch results, we settle the bill — if fewer profiles were found, the excess credits are refunded automatically.
     *
     * **Filters:** Narrow results by country, job title, department, or seniority level.
     *
     * **Webhooks:** Optionally pass a `webhookUrl` to automatically receive one webhook per follower profile as it's scraped, plus a final completion callback when the job finishes. No separate flag needed — providing the URL enables per-result webhooks.
     *
     * @param {EnrichApi.CompanyFollowerRequest} request
     * @param {CompanyFollowersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.BadRequestError}
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.PaymentRequiredError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     * @throws {@link EnrichApi.InternalServerError}
     *
     * @example
     *     await client.companyFollowers.startCompanyFollowerScrape({
     *         companyUrl: "https://linkedin.com/company/stripe",
     *         max_limit: 500
     *     })
     */
    public startCompanyFollowerScrape(
        request: EnrichApi.CompanyFollowerRequest,
        requestOptions?: CompanyFollowersClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.StartCompanyFollowerResponse> {
        return core.HttpResponsePromise.fromPromise(this.__startCompanyFollowerScrape(request, requestOptions));
    }

    private async __startCompanyFollowerScrape(
        request: EnrichApi.CompanyFollowerRequest,
        requestOptions?: CompanyFollowersClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.StartCompanyFollowerResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "company-follower",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as EnrichApi.StartCompanyFollowerResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new EnrichApi.BadRequestError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 402:
                    throw new EnrichApi.PaymentRequiredError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 500:
                    throw new EnrichApi.InternalServerError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/company-follower");
    }

    /**
     * > **Access required** — This endpoint is available to approved accounts only. [Contact us](https://enrich.so) to request access.
     *
     * Poll this endpoint to track the progress of your company follower scrape.
     *
     * **Cost:** Free — polling never costs credits.
     *
     * @param {EnrichApi.GetCompanyFollowerProgressRequest} request
     * @param {CompanyFollowersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.NotFoundError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     *
     * @example
     *     await client.companyFollowers.getCompanyFollowerProgress({
     *         batchId: "665a1f4e2c3b7800129dce01"
     *     })
     */
    public getCompanyFollowerProgress(
        request: EnrichApi.GetCompanyFollowerProgressRequest,
        requestOptions?: CompanyFollowersClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.CompanyFollowerProgressResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getCompanyFollowerProgress(request, requestOptions));
    }

    private async __getCompanyFollowerProgress(
        request: EnrichApi.GetCompanyFollowerProgressRequest,
        requestOptions?: CompanyFollowersClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.CompanyFollowerProgressResponse>> {
        const { batchId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `company-follower/${core.url.encodePathParam(batchId)}/progress`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as EnrichApi.CompanyFollowerProgressResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 404:
                    throw new EnrichApi.NotFoundError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/company-follower/{batchId}/progress",
        );
    }

    /**
     * > **Access required** This endpoint is available to approved accounts only. [Contact us](https://enrich.so) to request access.
     *
     * Returns paginated follower profiles for a completed batch. Use `page` and `limit` query params to paginate through results.
     *
     * Credits are charged upfront when you start the scrape. If fewer profiles are found than `max_limit`, unused credits are refunded automatically.
     *
     * If you provided a `webhookUrl`, results are already delivered via webhooks and credits are auto-settled. No need to call this endpoint.
     *
     * Only call this after the progress endpoint reports `done: true`.
     *
     * @param {EnrichApi.GetCompanyFollowerResultsRequest} request
     * @param {CompanyFollowersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.NotFoundError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     *
     * @example
     *     await client.companyFollowers.getCompanyFollowerResults({
     *         batchId: "665a1f4e2c3b7800129dce01"
     *     })
     */
    public getCompanyFollowerResults(
        request: EnrichApi.GetCompanyFollowerResultsRequest,
        requestOptions?: CompanyFollowersClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.CompanyFollowerResultsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getCompanyFollowerResults(request, requestOptions));
    }

    private async __getCompanyFollowerResults(
        request: EnrichApi.GetCompanyFollowerResultsRequest,
        requestOptions?: CompanyFollowersClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.CompanyFollowerResultsResponse>> {
        const { batchId, page, limit } = request;
        const _queryParams: Record<string, unknown> = {
            page,
            limit,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `company-follower/${core.url.encodePathParam(batchId)}/results`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as EnrichApi.CompanyFollowerResultsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 404:
                    throw new EnrichApi.NotFoundError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/company-follower/{batchId}/results",
        );
    }

    /**
     * > **Access required** — This endpoint is available to approved accounts only. [Contact us](https://enrich.so) to request access.
     *
     * Download scrape results as a CSV file. Batch must be complete. No credits consumed.
     *
     * @param {EnrichApi.ExportCompanyFollowerCsvRequest} request
     * @param {CompanyFollowersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.BadRequestError}
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.NotFoundError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     *
     * @example
     *     await client.companyFollowers.exportCompanyFollowerCsv({
     *         batchId: "batchId"
     *     })
     */
    public exportCompanyFollowerCsv(
        request: EnrichApi.ExportCompanyFollowerCsvRequest,
        requestOptions?: CompanyFollowersClient.RequestOptions,
    ): core.HttpResponsePromise<string> {
        return core.HttpResponsePromise.fromPromise(this.__exportCompanyFollowerCsv(request, requestOptions));
    }

    private async __exportCompanyFollowerCsv(
        request: EnrichApi.ExportCompanyFollowerCsvRequest,
        requestOptions?: CompanyFollowersClient.RequestOptions,
    ): Promise<core.WithRawResponse<string>> {
        const { batchId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `company-follower/${core.url.encodePathParam(batchId)}/export`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            responseType: "text",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as string, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new EnrichApi.BadRequestError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 404:
                    throw new EnrichApi.NotFoundError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/company-follower/{batchId}/export",
        );
    }

    /**
     * Check your team's daily company follower scraping limit and current usage. No credits consumed.
     *
     * **Possible statuses:**
     * - `approved` — Team has access; `creditsPerProfile`, `dailyLimit`, `dailyUsed`, and `dailyRemaining` are included.
     * - `pending` — Application is under review.
     * - `rejected` — Application was rejected.
     * - `revoked` — Access was revoked.
     * - `none` — No application on file.
     *
     * @param {CompanyFollowersClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link EnrichApi.UnauthorizedError}
     * @throws {@link EnrichApi.TooManyRequestsError}
     * @throws {@link EnrichApi.InternalServerError}
     *
     * @example
     *     await client.companyFollowers.checkCompanyFollowerLimit()
     */
    public checkCompanyFollowerLimit(
        requestOptions?: CompanyFollowersClient.RequestOptions,
    ): core.HttpResponsePromise<EnrichApi.CheckCompanyFollowerLimitResponse> {
        return core.HttpResponsePromise.fromPromise(this.__checkCompanyFollowerLimit(requestOptions));
    }

    private async __checkCompanyFollowerLimit(
        requestOptions?: CompanyFollowersClient.RequestOptions,
    ): Promise<core.WithRawResponse<EnrichApi.CheckCompanyFollowerLimitResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "company-follower/limit",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as EnrichApi.CheckCompanyFollowerLimitResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new EnrichApi.UnauthorizedError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 429:
                    throw new EnrichApi.TooManyRequestsError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                case 500:
                    throw new EnrichApi.InternalServerError(
                        _response.error.body as EnrichApi.ErrorEnvelope,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.EnrichApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/company-follower/limit");
    }
}
